### ISSUE TITLE
Add comparison with `erofs` (present Linux mainline since 5.x)

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#10]
Apparently the `erofs` read-only file-system has made it into the mainline stable Linux kernel (since 5.x):
> https://www.kernel.org/doc/html/latest/filesystems/erofs.html

Therefore it would be nice to compare `dwarfs` against `erofs`, especially since its purpose seems similar (i.e. performance).

From my own limited experimentation with `erofs` it seems to be twice as fast compared to `squashfs`.

For example compressing `dwarfs` own source folder and build folder (with a block size of 4 KiB and using LZ4 or LZ4HC where possible), yields the following:
~~~~
# mkdwarfs -i . -o /tmp/dwfs.img -l 9 -S 12 -C lz4hc --no-owner --no-time
197M    /tmp/dwfs.img

# mkdwarfs -i . -o /tmp/dwfs.img-d --no-owner --no-time
114M    /tmp/dwfs.img-d

# mkfs.erofs -z lz4,9 -x -1 -T 0 -E force-inode-extended -- /tmp/erofs.img .
216M    /tmp/erofs.img

# mksquashfs . /tmp/sqfs.img -b 4K -reproducible -mkfs-time 0 -all-time 0 -no-exports -no-xattrs -all-root -progress -comp lz4 -Xhc -noappend
196M    /tmp/sqfs.img
~~~~

Mounting them and reading yields:
* `erofs` ~900 MiB/s, no difference on repeats;
* `squashfs` ~400 MiB/s, no difference on repeats;
* `dwarfs` (4KB) ~250 MiB/s, and on repeat ~900 MiB/s;
* `dwarfs` (all defaults) ~300 MiB/s, and on repeat ~900 MiB/s;

Thus, and this is a guess, I would say that `erofs` is as fast as `dwarfs`, at least on repeat reads (although all images were stored on `tmpfs`).

**Comment by mhx** [comment]
Didn't know about `erofs`, so thanks for the pointer! What I'm getting from a quick read, though, is that it has objectives that are quite different from DwarFS. Using DwarFS with block sizes of 4 KiB is just a bad idea to begin with. Everything DwarFS does that give it a reasonable advantage over other compressed file systems assumes that you're using reasonably large blocks (i.e. 1 MiB and larger).

Side note: `--no-owner` didn't work at all in 0.2.0 until it got replaced with `--set-(owner|group)`.

**Comment by mhx** [comment]
https://github.com/mhx/dwarfs#with-erofs

**Comment by krasnh** [comment]
[With EROFS](https://github.com/mhx/dwarfs?tab=readme-ov-file#with-erofs)
>It is not designed to provide maximum compression. It currently supports LZ4 and LZMA compression.

Added zstd support starting with erofs-utils 1.8. You can update the tests if it changes anything.

**Comment by mhx** [comment]
> [With EROFS](https://github.com/mhx/dwarfs?tab=readme-ov-file#with-erofs)
> >It is not designed to provide maximum compression. It currently supports LZ4 and LZMA compression.
> 
> Added zstd support starting with erofs-utils 1.8. You can update the tests if it changes anything.

That will likely only affect read performance, similar to DwarFS. It very likely won't impact compression ratio much (other than probably being worse compared to LZMA).

**Comment by krasnh** [comment]
News to inform the developer.
META announced an evolutionary leap in the development of compressors and provided OpenZL to replace Zstandard, which had reached a dead end, according to them.

https://engineering.fb.com/2025/10/06/developer-tools/openzl-open-source-format-aware-compression-framework/

**Comment by mhx** [comment]
> News to inform the developer.

Commenting on a closed, unrelated issue is probably not the best approach, though...

> META announced an evolutionary leap in the development of compressors and provided OpenZL to replace Zstandard, which had reached a dead end, according to them.

I'm aware of OpenZL. It certainly looks interesting, but:

- I don't think it's meant to "replace Zstandard"; they even say "However, this is no magic bullet. When OpenZL doesn’t understand the input file format, it simply falls back to zstd."
- It is certainly not mature enough (yet) that I would use it for archiving, especially given [this statement](https://github.com/facebook/openzl?tab=readme-ov-file#project-status):

> In particular, payloads compressed with any release-tagged version of the library will remain decompressible by new releases of the library for at least the next several years. And new releases of the library will be able to generate frames compatible with at least the previous release.
