### ISSUE TITLE
dwarfsextract (and likely other components too) may print garbage to console

### ISSUE THREAD

**Issue by galtgendo** [mhx/dwarfs#105]
Both src/dwarf/console_writer.cpp and src/dwarf/logger.cpp use `::strrchr(file, '/')` without accounting for that it may return NULL.

Something like this might be a solution:

```c++
    auto h_str = ::strrchr(file, '/');
    context = fmt::format("[{0}:{1}] ", h_str ? h_str + 1 : file, line);
```

...not sure though if it's a correct one.

**Comment by mhx** [comment]
Hi @galtgendo! Thanks for the report!

Yeah, I agree this is a bug. Just wondering: were you able to actually make it print garbage? Or is this just a theoretical issue? The `file` parameter should always contain a compiler generated string with the path of the source file. At least with the way the source code is currently organised, I would always expect there to be a `/` in the string.

**Comment by galtgendo** [comment]
Actually, I did.
Not passing a path to dwarfsextract was all it took.

**Comment by mhx** [comment]
> Not passing a path to dwarfsextract was all it took.

Can you elaborate? What path do you mean? `dwarfsextract` takes two path-like arguments (`--input` and `--output`). If you leave out one of them, you should simply get an error. (Sorry, I'm just really trying to understand this...)

**Comment by mhx** [comment]
Oh, wait a second. Have you been trying something like this?
```
dwarfsextract -i foo.dwarfs -f gnutar
```
The `--output` flag is optional (you'll still get an error if there's a stray `--output` on the command line without an argument). If you explicitly pass a format (using `-f`) and leave out the `--output` flag, then the output gets written to `stdout` so that it can be passed to another tool (e.g. `tar`).

Please post the exact command line that you used to produce the problem you're seeing.

**Comment by galtgendo** [comment]
Well, it's been awhile and my use of dwarfs was likely one-off for quite awhile, but there are some hints that the command used was something like `dwarfsextract -i blob.dwarfs -o test`.

**Comment by mhx** [comment]
I've tried all of these commands with the 0.6.1 release, they all either worked as expected or failed as expected (e.g. `-o test` would fail if `test` didn't exist or wasn't a directory).
