### ISSUE TITLE
Question about read-only vs read-write

### ISSUE THREAD

**Issue by xyproto** [mhx/dwarfs#11]
Hi,

DwarFS looks absolutely brilliant. But are there any plans to make it read-write, or is the plan to keep it as a read-only file system?

I would love to try it out for checking out several large (and similar, but different) git repositories, and then building them. We have several 300GB repositories at work, but most developers only have a 1T disk, so it quickly fills up.

Would you recommend an overlay filesystem on top of DwarFS for this use case, for now?

Thanks!

**Comment by mhx** [comment]
To be completely honest, the plan is for DwarFS to be as simple as necessary to achieve its job. Adding a read-write layer would add significant complexity and is completely outside the scope of what I'm planning to do.

As for your use case, I'm sceptical. Git itself already uses compression under the hood, and already compressed files are notorious for compressing badly, so I don't have much hope that you'll be able to save a significant amount of disk space that way. Just try making a tar archive of your `.git` tree and then try to compress that with a tool of your choice. You'll likely find that you don't save more than 10%, and that's probably better than what you'd be able to get from DwarFS.

**Comment by cipriancraciun** [comment]
@xyproto 

Although I agree with @mhx about the fact that DwarFS should be as simple as possible (thus no write option), I do think it can be useful for such Git repositories as you are describing.

However it's not straightforward but it can be done (these are not tested but based on my previous experiments should could work):
* **obviously I strongly suggest backing up things before this!**
* (optional) make sure your "base" repositories contain no unreferenced commits:
~~~~
git reflog expire --all --expire=all --expire-unreachable=all
git pack-refs --all

nice -n 19 -- git prune --expire=all --verbose
nice -n 19 -- git repack -A -d
nice -n 19 -- git prune --expire=all --verbose
nice -n 19 -- git fsck --root --tags --no-reflogs --full --connectivity-only --unreachable --dangling --name-objects
~~~~
* create an empty and "bare" git repository, let's call this "seed";
* find all `.pack` files from all your other repositories and call `git unpack-objects /absolute-path-to-other-git/objects/pack/something.pack` from within the "seed" repository;  (this will extract all objects, including commits, etc. in the shared "seed" git repository;)
* now your "seed" repository contains every object and commit all your other repositories contain;  (however it isn't useful for actual development;)
* (optional) before you proceed with DwarFS, try to see if `git repack -a -k` in the "seed" repository doesn't make things better;  make a backup of your "seed" repository first, or you'll have to unpack objects again;
* (optional) perhaps try to pack as above but instruct `git` not to compress anything;  also note that `git` has its own delta algorithm (I would perhaps disable that) and the option to limit the size of a pack file (I would also try to use this);  (without `.pack` files Git would have to access lots of commits and things could be quite slow just for this reason;)
* try to use DwarFS on the `.git/objects` folder from the "seed" repository;
* create empty new repositories for your original projects;
* use the `.git/objects/info/alternates` feature to point to the "seed" objects folder that you've just compressed with DwarFS;
* recreate the tags and branches (perhaps by doing a `git fetch /path-to-original-project/.git 'refs/*:refs/*'`);
* any new commits would just be created in each new repository, but objects from the "seed" would be reused from DwarFS;

As time passes, you can continue updating your DwarFS by importing new packs from other repositories and pruning them from the clones.

As such, perhaps if you apply the above DwarFS could be totally optional as things might just work without it.  (However DwarFS is useful for the fact that it provides a read-only file-system so it's quite difficult to destroy your "seed" repository.)

**Comment by xyproto** [comment]
@cipriancraciun Thanks for the detailed instructions! I will try them out.
