### ISSUE TITLE
Short silent/quiet output option for mounting

### ISSUE THREAD

**Issue by Phantop** [mhx/dwarfs#113]
This is a small thing, but I think useful if you're constantly mounting and remounting images. I know that you can pass `-o debuglevel=warn`, however a lot of other mounting tools don't give output when mounting successfully, and many programs in general have a `-q` option, so working one in would be a nice small convenience thing.

**Comment by mhx** [comment]
Popular counterexample...
```
root@air ~ # mount -r /dev/sdb1 /mnt/tmp/
FUSE exfat 1.3.0
```
But I agree. Instead of adding yet another option, however, I'm going to make the debuglevel default to `warn` in background mode. In foreground mode (`-f`, `-d`), it'll still default to `info`.
