### ISSUE TITLE
systemd recipe?

### ISSUE THREAD

**Issue by rurban** [mhx/dwarfs#12]
I'm struggling to come up with a proper systemd recipe. I'm a systemd noob.
When starting it as systemd service dependent on local-fs my mount is not readable by the local user.

```
systemctl enable dwarfs-mount
systemctl start dwarfs-mount
```

```
$ ls -al
drwxr-xr-x.  5 rurban 69632 Nov 30 13:48 perl
d??????????  ? ?          ?            ? perl.s
```

when starting it locally it works fine.
```
sudo cat /etc/systemd/user/dwarfs-mount.service
[Unit]
Description=Local DwarfFS Mounts
Documentation=man:dwarfs(1) https://github.com/mhx/dwarfs
DefaultDependencies=no
#ConditionKernelCommandLine=
OnFailure=emergency.target
Conflicts=umount.target
# Run after core mounts
After=-.mount var.mount
After=systemd-remount-fs.service
# But we run *before* most other core bootup services that need write access to /etc and /var
#Before=local-fs.target umount.target
#Before=systemd-random-seed.service plymouth-read-write.service systemd-journal-flush.service
#Before=systemd-tmpfiles-setup.service

[Service]
Type=oneshot
User=rurban
Group=root
RemainAfterExit=yes
ExecStart=/usr/local/bin/dwarfs /usr/src/perl/perl.dwarfs /usr/src/perl.s
StandardInput=null
StandardOutput=journal
StandardError=journal+console

[Install]
WantedBy=local-fs.target

```

Or maybe should I just add it to my fstab?

EDIT: **Beware** With an syntax error in such a system unit, depending on local-fs, you can lock yourself out and need to boot from USB. emergency mode i.e. rescue.target will not work.

**Comment by mhx** [comment]
I'd try to just add it to fstab. I've actually never done that (I just ran the fuse driver), so let me know how it goes!

**Comment by cipriancraciun** [comment]
@rurban I would suggest switching to `Type=simple`, removing `RemainAfterExit` and running `dwarfs` with `-f` (for foreground) flag.

If that still fails, then perhaps add an `/usr/bin/strace -f` in front of `dwarfs` to see exactly what fails.

BTW, you can also use `systemd.mount` units (which are equivalent to `/etc/fstab` entries), but can have all the dependencies a normal service has.  (Using a `.service` unit type has the advantage of being able to configure various resource constraints, sandboxing, etc.)

**Comment by mhx** [comment]
$ ls -al
    drwxr-xr-x.  5 rurban 69632 Nov 30 13:48 perl
    d??????????  ? ?          ?            ? perl.s

Ah, didn't see this before on my phone... this is a known fuse problem. You need to pass `-o allow_root`, otherwise `root` won't be able to access the dwarfs mountpoint. In order to use that option, you'll likely also have to uncomment `user_allow_other` in you `/etc/fuse.conf`.

I'll add this to the documentation along with setting up a read-write overlay.

**Comment by mhx** [comment]
Please check out https://github.com/mhx/dwarfs/blob/main/doc/dwarfs.md#setting-up-a-writable-file-system-on-top-of-a-dwarfs-image

**Comment by rurban** [comment]
Yes, but these instructions are not persistant. overlays are nice for write, but ro is fine for me.

I'll go with the fstab settings with some options for now. 
Also, maybe the binaries should be installed into sbin per default.

**Comment by RarogCmex** [comment]
+1 for support /etc/fstab

**Comment by RarogCmex** [comment]
You might look at sshfs (support fstab links)

**Comment by mhx** [comment]
`/etc/fstab` setup documented [here](https://github.com/mhx/dwarfs/blob/next-release/doc/dwarfs.md#adding-a-dwarfs-image-to-etcfstab) for the next release.

FUSE driver plus `mount.dwarfs` symlink will be installed to `$prefix/sbin` in the [next release](https://github.com/mhx/dwarfs/tree/next-release).

**Comment by mhx** [comment]
I'm closing this. I'm mostly unfamiliar with systemd, but it seems to me that `/etc/fstab` is a more natural and much easier way to set up mount rules for dwarfs.
Please re-open (or preferably send a PR) if you think systemd is the way to go.

**Comment by rurban** [comment]
Fine for me. I hate systemd, and it even bricked my system when I had a minor syntax error.
fstab is much more stable. Thanks.
