### ISSUE TITLE
Older fuse3 version

### ISSUE THREAD

**Issue by CaptainFrosty** [mhx/dwarfs#128]
Hi, I am trying to build on pengwin which uses Debian bullseye repos and my fuse3 version is `3.10.3` instead of `3.10.5`. So the build fails. Is there a way around this or do I have to upgrade it manually? Thanks.

**Comment by mhx** [comment]
I'm quite confident it should Just Work™ if you change the requirement in the toplevel `CMakeLists.txt`. If you can confirm that the test suite passes with `3.10.3`, I'm happy to change the requirement. Thanks!

**Comment by mhx** [comment]
I'll close this for now as the `CMakeLists.txt` now has a (strict) dependency on cmake 3.24.0.
