### ISSUE TITLE
Error at 44% while compiling on a Raspberry Pi 4 with Raspberry Pi OS (arm64)

### ISSUE THREAD

**Issue by samthelion17** [mhx/dwarfs#129]
As the title says, i'm getting this specific error: 
`In file included from /home/pi/dwarfs/folly/folly/experimental/io/AsyncIoUringSocket.h:30,
                 from /home/pi/dwarfs/folly/folly/experimental/io/AsyncIoUringSocket.cpp:18:
/home/pi/dwarfs/folly/folly/experimental/io/IoUringBackend.h: In member function ‘bool folly::IoUringBackend::IoSqe::EventCallbackData::processCb(folly::IoUringBackend*, int, uint32_t)’:
/home/pi/dwarfs/folly/folly/experimental/io/IoUringBackend.h:659:27: error: ‘IORING_CQE_F_MORE’ was not declared in this scope; did you mean ‘IORING_CQE_F_BUFFER’?
  659 |             if (!(flags & IORING_CQE_F_MORE)) {
      |                           ^~~~~~~~~~~~~~~~~
      |                           IORING_CQE_F_BUFFER
`
I've also tried googling without getting a single result, does anyone knows how can I solve this? I would settle for the arm64 binaries too!
here's the whole build log from the git clone to the error: https://pastebin.com/dL8AE8cV

**Comment by samthelion17** [comment]
So, I got it to compile, but take my solution with a grain of salt because i'm no developer (I can barely do light bash scripting).
What I did was, basically, follow the compiler's suggestion: I edited this two files
`./folly/folly/experimental/io/IoUringBackend.cpp`
`./folly/folly/experimental/io/IoUringBackend.h`
and changed all the occurrences of
`IORING_CQE_F_MORE`
for
`IORING_CQE_F_BUFFER`
on both of them.

I also commented out line #1573
`// io_uring_prep_cancel64(sqe, (uint64_t)ioSqe, 0);`

I'm leaving this issue open until a real dev shows up and closes it

**Comment by mhx** [comment]
Thanks for the report!

Just few quick notes:

- FWIW, I've just tried building the `main` branch on `5.19.8-1-aarch64-ARCH`. I don't have any `arm64` install I could test with right now.
- The changes you made are likely incorrect, but it doesn't matter for the purposes of Dwarfs as that code will never execute. This isn't the first time I've been running into issues related to Uring abstractions, prefereably I'd like to just switch off that code in `folly`, I'll have to take a look into that again.

**Comment by mhx** [comment]
I've just put out a release candidate that builds fine on `aarch64` and even includes static binaries for download. I'll close this for now, let me know if it's still an issue.
