### ISSUE TITLE
Feature Request: Support for Block-based Deduplication

### ISSUE THREAD

**Issue by wychen** [mhx/dwarfs#137]
I would like to propose a feature request to add support for block-based deduplication in DwarFS. Currently, the file system supports file-based deduplication, which provides significant storage savings for duplicate files. However, block-based deduplication would offer additional benefits by identifying and eliminating redundant blocks within and across files, leading to even greater storage efficiency. For example, two large files with minor content differences, like two uncompressed tar files containing some duplicated files, would benefit from block-based deduplication.

I don't have a deep understanding of the file format, but it looks like we might be able to achieve this without breaking compatibility. If we deduplicate the chunks according to their hashes, files with very similar blocks could reuse these chunks. Two identical files would share the same offset in the `chunk_table`, but if these two files are slightly different, we can duplicate the entries in the `chunk_table` and only replace the different blocks, while reusing the majority of the chunks.

If we push this concept further, we can even use a content-defined chunker so that the chunks don't need to be address-aligned. This could detect identical chunks that are not aligned, like JPEG files with identical images but different sized EXIF header. This content-defined chunker is inspired by the rsync algorithm and borg chunker as described in https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html.

Does this make sense? I'm happy to discuss further and would appreciate any feedback.

**Comment by Phantop** [comment]
DwarFS already does this! It's referred to as the segmenting step, and is a major part of its efficacy as a deduplicating filesystem.

**Comment by mhx** [comment]
@Phantop is correct, this is already implemented.

Chunks/segments don't need to be aligned, but they cannot be arbitrarily small (for various reasons). The segmenter uses a moving window (`-W`) and remembers hash values in evenly spaced steps (`-w`). The window is moved one byte at a time and checked against the remembered hashes of the `-B` latest blocks. Bloom filters are used internally (`--bloom-filter-size`) to make this lookup efficient. Once a match is found (and verified), the match is extended as far as possible in both directions and a reference is made by means of a metadata chunk. So what you describe (JPEG with identical image but different EXIF data) already works.

One similar use case that was discussed (#63) in the past was videos with different audio tracks. Given the right set of options, `mkdwarfs` was able to fully deduplicate the audio/video chunks for the different video files.

I'll close this for now, but feel free to reopen if I misunderstood something.

**Comment by wychen** [comment]
@Phantop @mhx Thank you both for the clarification, and I apologize for not going through the documentation thoroughly before raising this issue. I appreciate your detailed responses and the existing functionality in DwarFS. Keep up the great work!
