### ISSUE TITLE
Make file utility (guess file type) recognize dwarfs images instead of being unknown file type.

### ISSUE THREAD

**Issue by adminx01** [mhx/dwarfs#144]
The file type guessing utility on GNU/Linux fails to determine the file type of dwarfs images and shows them as an unknown type. It would be a nice improvement to fix that and get some proper recognition of the format.

**Comment by CheerfulPianissimo** [comment]
Seems simple enough with the file format  [spec]([https://github.com/mhx/dwarfs/blob/main/doc/dwarfs-format.md) . There's the 'DWARFS' magic string followed by two bytes containing the major and minor version numbers. I've created an issue on `file`'s issue tracker with the magic file attached: [https://bugs.astron.com/view.php?id=449](https://bugs.astron.com/view.php?id=449) . 

It can be tested using `file -m dwarfs.magic example.dwarfs` . Here's [dwarfs.magic](https://bugs.astron.com/file_download.php?file_id=336&type=bug).

**Comment by mhx** [comment]
Thanks for your contribution @CheerfulPianissimo!

Also thanks to @adminx01 to get this started!

I think the magic file can be improved, though:

First, only checking for `DWARFS` at the start is probably a bit lax. It's relatively easy to reach the second block from the first one and check its magic as well, which makes it much harder to create a matching file by accident.

Second, DwarFS images support arbitrary headers at the start of the file. This isn't currently documented in the format spec, but I'll update that later. This case is a bit trickier and it took me a while to figure out how to solve this using the constraints of the magic file syntax.

I'll post an update to your issue with my files attached.

**Comment by mhx** [comment]
FYI, I filed a new issue as yours got resolved while I was writing the update: https://bugs.astron.com/view.php?id=451

**Comment by mhx** [comment]
The magic files have been merged into the `file` repo, so I'll close this issue for now. Feel free to reopen or file another issue in case of problems.

**Comment by mhx** [comment]
Mmmmh, odd. I've just updated and pulled from https://github.com/file/file, built and installed the binary locally. Running it against some DwarFS images, I get:

```
$ ~/bin/file/bin/file *.dwarfs 
include-header.dwarfs:   Bourne-Again shell script executable (binary data)
include.dwarfs:          DwarFS File System Image, version 2.4, LZ4 compression
magictest-header.dwarfs: Bourne-Again shell script executable (binary data)
magictest.dwarfs:        DwarFS File System Image, version 2.4, ZSTD compression
mount.dwarfs:            symbolic link to dwarfs
rasp-norm.dwarfs:        DwarFS File System Image, version 2.4, LZ4 compression
rasp-norm2.dwarfs:       DwarFS File System Image, version 2.4, LZ4 compression
```

This all makes sense to me. The files with `-header` contain a shell script in front of the file system, so the classification makes sense. `mount.dwarfs` is really just a symlink to `dwarfs` and not a file system. All other images are correctly identified.

Can you figure out exactly which git commit your binary is built from?

I wonder if there's another SIMH mis-classification happening, as very recently seems to have been the case: https://bugs.astron.com/view.php?id=450.
