### ISSUE TITLE
Broken build?

### ISSUE THREAD

**Issue by M-Gonzalo** [mhx/dwarfs#152]
I'm trying to compile the latest release and I get this:

![image](https://github.com/mhx/dwarfs/assets/23223606/e390027d-291d-4882-a615-ff3c596dc463)

I'm on Linux, up-to-date
Commands:
```bash
git clone --recurse-submodules https://github.com/mhx/dwarfs && cd dwarfs
mkcd build
cmake .. -DWITH_TESTS=1
make -j $(nproc)
```
Edit: forgot it's in Spanish. It says it can't find the file in red

**Comment by mhx** [comment]
This is a new dependency. You'll have to install `libutfcpp-dev` (or the equivalent of that for your package manager). I've updated this [in the docs](https://github.com/mhx/dwarfs#dependencies) as well. :)

You can always check [here](https://github.com/mhx/dwarfs/actions) if the latest version builds fine on Ubuntu or Windows.

**Comment by mhx** [comment]
This is a new dependency. You'll have to install `libutfcpp-dev` (or the equivalent of that for your package manager). I've updated this [in the docs](https://github.com/mhx/dwarfs#dependencies) as well. :)

You can always check [here](https://github.com/mhx/dwarfs/actions) if the latest version builds fine on Ubuntu or Windows.

**Comment by M-Gonzalo** [comment]
It worked, thanks!
