### ISSUE TITLE
fatal error: utf8cpp/utf8.h: No such file or directory

### ISSUE THREAD

**Issue by Belamat** [mhx/dwarfs#153]
Hi, Im on Fedora 37 and this error occurred, not sure how to proceed. 
Appreciate your help. 
Thanks.

[ 81%] Building CXX object CMakeFiles/dwarfs.dir/src/dwarfs/util.cpp.o
/home/ton/dwarfs/util.cpp:26:10: fatal error: utf8cpp/utf8.h: No such file or directory
   26 | #include <utf8cpp/utf8.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dwarfs.dir/build.make:594: CMakeFiles/dwarfs.dir/src/dwarfs/util.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:439: CMakeFiles/dwarfs.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by mhx** [comment]
Hi there!

You're missing a dependency: [utfcpp](https://github.com/nemtrif/utfcpp). On Debian/Ubuntu this is available as `libutfcpp-dev`, not sure about Fedora, though. It should be fairly easy to install even without a pre-built package.

Your other alternative is to just use the pre-built binaries from the [Releases](https://github.com/mhx/dwarfs/releases) page.

**Comment by mhx** [comment]
Feel free to reopen the issue if you still have problems.

**Comment by Belamat** [comment]
thanks for the reply, couldnt find that dependency for Fedora.

tried to compile [dwarfs-0.7.0](https://github.com/mhx/dwarfs/releases/tag/v0.7.0)  inside the main folder doing 
make build
 cd build
 cmake .. -DWITH_TESTS=1
 make -j$(nproc) 

but the same utf8cpp error appears (not sure if that is the way to compile it)

anyway I have the /usr/include/unicode/utf8.h in the unicode chars

**Comment by tpwrules** [comment]
Should this be added to the CMake files so that a more relevant error is given and the version is checked?

**Comment by mhx** [comment]
> Should this be added to the CMake files so that a more relevant error is given and the version is checked?

Possibly. I don't think there's any way to perform a version check for utfcpp, though. Happy to accept a PR :)

**Comment by tpwrules** [comment]
Ah, I assumed the utf8lib shipped with a .pc file in which case this would be easy, but evidently not.

**Comment by mhx** [comment]
Nah, it comes with a (pretty much useless) CMake config, but that's it. As far as I can tell, even the headers themselves don't have any version information.

**Comment by gudenau** [comment]
I have version 4.0.1 installed and CMake can't find it for me.

**Comment by mhx** [comment]
> I have version 4.0.1 installed and CMake can't find it for me.

Yeah, sorry, the utfcpp header files were moved to a different install location with the 4.x releases. There's a [bug report](https://github.com/nemtrif/utfcpp/issues/112), but that got closed without the actual issue being fixed. I've just sent a [pull request](https://github.com/nemtrif/utfcpp/pull/115). Until then, can you downgrade to a 3.x version of utfcpp?
