### ISSUE TITLE
fusermount3: mounting over filesystem type 0x7366746e is forbidden

### ISSUE THREAD

**Issue by Fabxx** [mhx/dwarfs#162]
I don't know why this is happening, but i'm trying to mount this dwarfs on a NTFS partition, before a system update on arch linux this was fine, but now it's acting like this. i did some research but i couldn't find this error code anywhere.

i can only mount via sudo, but the hard drive it's not locked behind root permissions

**Comment by mhx** [comment]
Can you please describe your exact environment? Are you using WSL? How are you mounting the NTFS partition? Are you able to mount any other FUSE-based file system in the same environment?

**Comment by Fabxx** [comment]
native arch linux, it's a 1TB disk that i mount normally when i click on it from tunar and i give my password to mount the NTFS partition, i can also mount ext4 ssd partition normally. The same thing doesn't seem to happen with another NTFS disk of 2TB

**Comment by mhx** [comment]
Can you please paste the exact commands you're using and their exact output? Ideally, show both, the case that works and the case that doesn't.

**Comment by Fabxx** [comment]
`dwarfs myfile.dwarfs mnt 
I 23:32:26.497181 dwarfs (v0.6.2, fuse version 35)
I 23:32:26.646246 file system initialized [149ms]
fusermount3: mounting over filesystem type 0x7366746e is forbidden`

2TB Disc command result:

`dwarfs custom.dwarfs Recovery/mnt 
I 23:34:35.428586 dwarfs (v0.6.2, fuse version 35)
I 23:34:35.428766 file system initialized [141.2us]`

both dwarfs were made with --compress-level=9

**Comment by mhx** [comment]
This error originates from the [fusermount code](https://github.com/libfuse/libfuse/blob/master/util/fusermount.c#L1038-L1078).

The [check is skipped when running as root](https://github.com/libfuse/libfuse/blob/master/util/fusermount.c#L957-L959).

I would assume the 2 TB (working) disk uses `NTFS_SB_MAGIC` (0x5346544E, which is in the list), whereas the 1 TB (failing) disk uses `NTFS3_SUPER_MAGIC` (0x7366746e, which isn't in the list).

Now, here's a completely random guess:

The system update you mentioned also updated the kernel, which now contains the NTFS3 driver. For some reason, the working drive is mounted using the *old* NTFS driver, the failing drive is mounted using the *new* NTFS3 driver. You can potentially check that by running `mount` without arguments and searching for your drive.

In any case, there is absolutely nothing DwarFS can do here. Please file an issue for [libfuse](https://github.com/libfuse/libfuse/issues), which will likely have to add `NTFS3_SUPER_MAGIC` to their fusermount filesystem magic whitelist.
