### ISSUE TITLE
Add support for Ubuntu

### ISSUE THREAD

**Issue by Frogsmune** [mhx/dwarfs#169]
Couldn't make a pull request so I am adding my own contribution in here. Managed to compile and install dwarfs on Ubuntu. Before compilation simply failed.

Dependencies to install:
sudo apt update
sudo apt install ruby-dev ronn libfuse-dev libboost-all-dev libdouble-conversion-dev libfmt-dev libgoogle-glog-dev libarchive-dev libjemalloc-dev

Then we need to compile UtfCpp. Link to it - https://github.com/nemtrif/utfcpp/.
***BEFORE COMPILING***
UtfCpp has an issue and I reported a fix of it to this library's team. Until it is not fixed by the developers, users will have to manually fix the issue which rises while trying to compile.
To fix the issue - take UtfCpp ftest.h file from their own repository in [here](https://github.com/nemtrif/ftest/blob/c4ad4af0946b73ce1a40cbc72205d15d196c7e06/ftest.h).

Move it to /UtfCpp/extern/ftest

Then go to /UtfCpp and open it it in terminal. From there compile and install the library.

make .
make
sudo make install

That is it. These are all dependencies for Ubuntu to successfully compile Dwarfs. All what is left to do is to follow compilation instructions provided by the team of Dwarfs.

**Comment by mhx** [comment]
Hi @Frogsmune, thanks for your input!

DwarFS should build fine on Ubuntu (unless you're trying a static build). In fact, all of the CI uses Ubuntu to continuously build DwarFS.

WRT `utfcpp`, installing `libutfcpp-dev` should be sufficient.

**Comment by mhx** [comment]
I'm closing this for now, but feel free to re-open in case there's still an issue.
