### ISSUE TITLE
how do I use you software?

### ISSUE THREAD

**Issue by lucasmz1** [mhx/dwarfs#178]
I need a way to make make a self contained linux app like an appimage but one that mount always in the same spot automatically on the system to execute the app. just like a simple container for an executable does your app do that ? what the command line paramenters?

**Comment by Phantop** [comment]
If you want to make an AppImage-like file, my own project, [`appdwarf`](https://github.com/phantop/appdwarf), might be of interest to you.

**Comment by lucasmz1** [comment]
thank you so much sir

**Comment by lucasmz1** [comment]
whats the command for appdwarf ? I have an appdir with everything inside what's the command to pack it?
