### ISSUE TITLE
The release bundles don't seem to contain dependencies

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#19]
I've just downloaded both 0.2.2 and 0.2.3 `tar.gz` bundles from GitHub (the releases pane on the right), and when trying to configure it with `cmake` it complains that it fails to find `CMakeLists.txt` in both `folly` and `fbthrift`.  Inspecting those folders they are empty.

Doing a `git clone` and submodules update does seem to fix the issue.

Thus it would be a good idea to include in the bundles those two dependencies, or update the readme to point out to users how to populate those folders.

**Comment by mhx** [comment]
Not sure what happened, but the tarball I uploaded with the 0.2.3 release was marked as broken by github when I went to "edit release". I've re-uploaded it now, so this should be fixed.

About the "source code" zip / tarball, these are autogenerated by github and I don't know of a way to modify (or even delete) them.

**Comment by mhx** [comment]
This should be fixed with the re-uploaded tarball.
