### ISSUE TITLE
Unable to detect duplicate data between game savefiles of 30Mb each

### ISSUE THREAD

**Issue by samuelwatsonofficial** [mhx/dwarfs#199]
I was testing how well the discovery of duplicate data within files works as I have a usecase where in the game Baldur's Gate 3, every save creates a new folder and new (progressively bigger) .lsv file (Larian Save File). With about 30Mb per save and a lot of saves this adds up to 7.6 gigabytes. I attempted to compress this with dwarfs as it seems like it would be very useful for detecting the similarity of data and saving a lot of space. 
I tested this with the parameters:
mkdwarfs -i Story/ -o Saves.dwarfs --compress-level=9

These are the files being tested, although i changed the names of the .lsv files to check if the problem was due to dissimilar filenames https://gofile.io/d/P1pBcI .
In my testing I found that mkdwarfs did not detect any duplication of data between these files which is unfortunate. I wondered if there was a problem due to the files being so small individually so I retested with smaller block sizes and higher block lookback checking but so far I have not found the .dwarfs file to be significantly smaller than the original folder.
Any input on what could be done to find the similarity between files more effectively would be appreciated, either a setting I missed or something to add to development (similarity checking is genuinely a hard problem to do fast, please don't feel this is a high priority if this usecase is not something you planned for).
If you need me to send the 7.6 gigabyte folder with all the saves for testing, I am more than happy to however I hope the saves I picked can demonstrate the duplicate data.
And as always thank you so much for making this project!

**Comment by Phantop** [comment]
Have you tried testing compressing them with something else? It's possible the save format for the game is already compressed and/or encrypted.

**Comment by samuelwatsonofficial** [comment]
That's a very good point! Larian does do compression in their 3d models using LZST (even though they should arguably use something else). I just did some testing with an extractor and you're right the files are compressed so cannot be compared like normal files. Sorry to bother you with this and thank you for your suggestion.
