### ISSUE TITLE
Grabbled output due to progress bar and mismatched `TERM`

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#20]
For some reason, if running `mkdwarfs` over SSH under `screen` from `urxvt` (i.e. `urxvt -e ssh user@host` then run `screen` then run `mkdwarfs`) the progress bar gets grabbled and outputs `â¯â¯â¯â¯â¯â¯`.

I've run `strace` and the progress bar seems to be written as:
~~~~
[pid 17539] write(2, "\342\216\257\342\216\257\342\216\257\342\216\257\342\216\257\342\216\257\342\216\257\342\216\257\342\216\257\342\216\257\342\216"..., 1206)
~~~~

Running with an empty environment (i.e. `env -i`) and even setting `TERM` to any of `vt100`, `linux`, `rxvt-unicode`, `screen`, `screen.rxvt`, `xterm` doesn't seem to fix it.

Granted if one doesn't use `screen` the progress bar looks OK.  (Although locally on my laptop, with a newer `screen` it does seem to work just fine.)

My assumption is that the progress bar characters trick `screen` into displaying wrong characters.

Perhaps add an option to use ASCII-only progress bar or `VT100` only compliant codes.  Alternatively, add an option to print the progress from time-to-time as simple `print` statements as opposed to the current nice progress dashboard.

**Comment by mhx** [comment]
There's already `--no-progress`, but yeah... that's annoying.

**Comment by cipriancraciun** [comment]
I know about `--no-progress`, but that just makes `mkdwarfs` silent until it finishes, which during tests (i.e. seeing how the compression goes) is suboptimal.

I was suggesting something "in-between", that uses "conventional" `stderr` printing (no fancy terminal escape codes, or at least `VT100` compliant ones, and ASCII only) from time to time to give an ideea of the progress.

BTW, this would also be useful for those wanting to automate `mkdwarfs` in CI/CD tools like Jenkins, which at the moment most likely also chokes on the progress bar.  Thus perhaps to cover also this use-case, an no escape codes solution would be best.

**Comment by mhx** [comment]
This will be in the next release:

    $ mkdwarfs -i ../../randomfiletree/random -o /dev/null --progress=none -l0
    20:13:23.812844 scanning ../../randomfiletree/random
    20:13:30.263489 waiting for background scanners...
    20:13:34.686842 assigning directory and link inodes...
    20:13:34.889559 finding duplicate files...
    20:13:35.808018 saved 0 B / 27.85 MiB in 0/811332 duplicate files
    20:13:35.808069 assigning device inodes...
    20:13:35.853997 assigning pipe/socket inodes...
    20:13:35.900484 building metadata...
    20:13:35.900533 building blocks...
    20:13:35.900598 saving names and links...
    20:13:35.900641 keeping inode order
    20:13:35.900721 assigning file inodes...
    20:13:36.000290 waiting for segmenting/blockifying to finish...
    20:13:37.794104 updating name and link indices...
    20:13:45.237698 saving chunks...
    20:13:45.254638 saving directories...
    20:13:47.275407 waiting for compression to finish...
    20:13:47.290508 compressed 27.85 MiB to 55.98 MiB (ratio=2.00954)
    20:13:48.158023 filesystem created without errors [24.35s]
    306693 dirs, 0/0 soft/hard links, 811332/811332 files, 0 other
    original size: 27.85 MiB, dedupe: 0 B (0 files), segment: 0 B
    filesystem: 27.85 MiB in 28 blocks (811356 chunks, 811332/811332 inodes)
    compressed filesystem: 28 blocks/55.98 MiB written
    
    $ mkdwarfs -i ../../randomfiletree/random -o /dev/null --progress=simple -l0
    20:13:52.839974 scanning ../../randomfiletree/random
    20:13:52.839989 ==> 0.0%
    20:14:00.569775 waiting for background scanners...
    20:14:05.336666 assigning directory and link inodes...
    20:14:05.529761 finding duplicate files...
    20:14:06.469620 saved 0 B / 27.85 MiB in 0/811332 duplicate files
    20:14:06.469663 assigning device inodes...
    20:14:06.509542 assigning pipe/socket inodes...
    20:14:06.549271 building metadata...
    20:14:06.549318 building blocks...
    20:14:06.549338 saving names and links...
    20:14:06.549397 keeping inode order
    20:14:06.549454 assigning file inodes...
    20:14:06.643507 waiting for segmenting/blockifying to finish...
    20:14:06.840665 ==> 1.7%
    20:14:08.418027 updating name and link indices...
    20:14:08.840794 ==> 60.9%
    20:14:10.840919 ==> 71.7%
    20:14:12.841044 ==> 82.7%
    20:14:14.841163 ==> 94.3%
    20:14:15.784995 saving chunks...
    20:14:15.802085 saving directories...
    20:14:16.841353 ==> 100.0%
    20:14:17.835100 waiting for compression to finish...
    20:14:17.850137 compressed 27.85 MiB to 55.98 MiB (ratio=2.00954)
    20:14:18.730713 filesystem created without errors [25.89s]
    306693 dirs, 0/0 soft/hard links, 811332/811332 files, 0 other
    original size: 27.85 MiB, dedupe: 0 B (0 files), segment: 0 B
    filesystem: 27.85 MiB in 28 blocks (811356 chunks, 811332/811332 inodes)
    compressed filesystem: 28 blocks/55.98 MiB written
    
    $ mkdwarfs -i ../../randomfiletree/random -o /dev/null --progress=ascii -l0
    20:14:23.421645 scanning ../../randomfiletree/random
    20:14:31.421740 waiting for background scanners...
    20:14:36.487540 assigning directory and link inodes...
    20:14:36.680014 finding duplicate files...
    20:14:37.579016 saved 0 B / 27.85 MiB in 0/811332 duplicate files
    20:14:37.579070 assigning device inodes...
    20:14:37.623392 assigning pipe/socket inodes...
    20:14:37.668896 building metadata...
    20:14:37.668963 building blocks...
    20:14:37.669023 saving names and links...
    20:14:37.669082 keeping inode order
    20:14:37.669166 assigning file inodes...
    20:14:37.772984 waiting for segmenting/blockifying to finish...
    20:14:39.625950 updating name and link indices...
    20:14:47.365521 saving chunks...
    20:14:47.382971 saving directories...
    20:14:49.419747 waiting for compression to finish...
    20:14:49.436003 compressed 27.85 MiB to 55.98 MiB (ratio=2.00954)
    20:14:50.277867 filesystem created without errors [26.86s]
    -----------------------------------------------------------------------------------------
    waiting for block compression to finish
    306693 dirs, 0/0 soft/hard links, 811332/811332 files, 0 other
    original size: 27.85 MiB, dedupe: 0 B (0 files), segment: 0 B
    filesystem: 27.85 MiB in 28 blocks (811356 chunks, 811332/811332 inodes)
    compressed filesystem: 28 blocks/55.98 MiB written
    ===================================================================================100% /
    
    $ mkdwarfs -i ../../randomfiletree/random -o /dev/null --progress=unicode -l0
    20:15:05.453302 scanning ../../randomfiletree/random
    20:15:12.761744 waiting for background scanners...
    20:15:17.857635 assigning directory and link inodes...
    20:15:18.050250 finding duplicate files...
    20:15:18.986683 saved 0 B / 27.85 MiB in 0/811332 duplicate files
    20:15:18.986744 assigning device inodes...
    20:15:19.031860 assigning pipe/socket inodes...
    20:15:19.077806 building metadata...
    20:15:19.077876 building blocks...
    20:15:19.077930 saving names and links...
    20:15:19.077985 keeping inode order
    20:15:19.078067 assigning file inodes...
    20:15:19.201897 waiting for segmenting/blockifying to finish...
    20:15:21.176650 updating name and link indices...
    20:15:29.085867 saving chunks...
    20:15:29.103989 saving directories...
    20:15:31.213940 waiting for compression to finish...
    20:15:31.229755 compressed 27.85 MiB to 55.98 MiB (ratio=2.00954)
    20:15:32.078981 filesystem created without errors [26.63s]
    ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
    waiting for block compression to finish
    306693 dirs, 0/0 soft/hard links, 811332/811332 files, 0 other
    original size: 27.85 MiB, dedupe: 0 B (0 files), segment: 0 B
    filesystem: 27.85 MiB in 28 blocks (811356 chunks, 811332/811332 inodes)
    compressed filesystem: 28 blocks/55.98 MiB written
    ██████████████████████████████████████████████████████████████████████████████████▏100% |

**Comment by cipriancraciun** [comment]
I confirm that by using `--progress ascii` everything looks OK now.

**Comment by mhx** [comment]
Cool, thanks!
