### ISSUE TITLE
[Feature request] Allow providing dwarfs with a dedup library

### ISSUE THREAD

**Issue by exeter-matthew-wakeling** [mhx/dwarfs#208]
This is really neat.

Feature request: Add a "library" option to give mkdwarfs a list of files that should be loaded into the dedup mechanism first, *but not stored*, allowing the image to be even smaller if the contents of the file can be retrieved from that library instead. Bonus points if you can specify a dwarfs image as a library and have it sensibly use the files contained in it.

Then you have the basis for a deduplicating incremental backup system. Currently, I have a system I wrote that will take a single file and a list of library files and produce a compressed deduplicated file that can re-create that single file using the library, which is great if you use tar to create that single file, but a little unwieldy when coming to decompress and restore everything. The bonus of making it a proper mountable filesystem instead is that then it's a proper mountable filesystem and retrieving single files is a doddle.

My use case is that I have students, and I have given them coursework, which involves them logging in to a Linux machine and hacking away. I want to store regular snapshots of their work so that I can keep a backup for their sake but also so I can see a progression of development to try to work out if they are cheating (yes, I have had to deal with this), but I don't want to store 100 copies of the same fairly large files. Yes, I could achieve the same thing using ZFS snapshots, but that'd require snapshotting the entire filesystem, which is more than I want to do, and it requires root.

**Comment by exeter-matthew-wakeling** [comment]
> only that everything will be contained in a single DwarFS image

That's a good idea, because it reduces the chances that the "library" will accidentally go missing. The only request I would make would be the ability to still mount or extract the older version of the filesystem.

**Comment by mhx** [comment]
Closing this as it's covered by #18.
