### ISSUE TITLE
official debian package, allow building without git?

### ISSUE THREAD

**Issue by alexmyczko** [mhx/dwarfs#209]
```
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- REAL_SOURCE_DIR: /var/www/debian/dwarfs/dwarfs-0.9.7 (/var/www/debian/dwarfs/dwarfs-0.9.7)
-- GIT_TOPLEVEL: /var/www/debian/dwarfs/dwarfs-0.9.7 ()
-- PRJ_GIT_REV: 
-- PRJ_GIT_DATE: 
CMake Error at cmake/version.cmake:54 (message):
  missing version files
Call Stack (most recent call first):
  CMakeLists.txt:143 (include)
```

wanted for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068852

**Comment by mhx** [comment]
You can either build *with* git, or use the release tarballs, which also contain the version files. Building from the [release tarball](https://github.com/mhx/dwarfs/releases/download/v0.9.7/dwarfs-0.9.7.tar.xz) would potentially be preferable for a Debian package?

You might want to take a look at #155 if neither of the above options work for you.

**Comment by alexmyczko** [comment]
perfect sorry for the double issue.

**Comment by mhx** [comment]
FYI, there are [several Dockerfiles](https://github.com/mhx/dwarfs/tree/main/.docker) in the repo that can be helpful in determining the set of dependencies.

**Comment by mhx** [comment]
I'll close this issue assuming that it doesn't require any changes for now. Please re-open or file a new issue if you still need support.
