### ISSUE TITLE
`mkdwarfs` refuses to start if the source is a symlink to a folder

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#21]
As the title says, if the given source argument is a symlink to a folder, `mkdwarfs` fails with an error stating it wants a folder.

As a workaround one could call `mkdwarfs -i .../folder/ -o .../output`.

I would suggest allowing (perhaps warning) a symlink to a folder as a source argument.

**Comment by mhx** [comment]
Just thought about this again while going through the open issues. Considering there's a really simple workaround and considering that e.g. `rsync` will sync the symlink without following it, I'm leaning towards keeping the behaviour as-is.
