### ISSUE TITLE
Gentoo ebuild for v0.10.0

### ISSUE THREAD

**Issue by mhx** [mhx/dwarfs#230]
FWIW, I've created a Gentoo ebuild for v0.10.0: [dwarfs-ebuild.tar.gz](https://github.com/user-attachments/files/16622166/dwarfs-ebuild.tar.gz)

This works around the usual issues with gtest and libfmt and exposes most build-time features as USE flags. Tested with both `FEATURES=ccache` and `FEATURES=test`.

@RarogCmex, feel free to update this in guru (I have no idea how this works).

**Comment by RarogCmex** [comment]
@mhx 
Thanks. I'm ill at this moment, I will update it when I will be able to.

**Comment by mhx** [comment]
> @mhx Thanks. I'm ill at this moment, I will update it when I will be able to.

No worries, hope you feel better soon!

**Comment by RarogCmex** [comment]
@mhx Could you update it to 0.10.1? I'll just place it to ::GURU then.

**Comment by mhx** [comment]
Here you go: 
[dwarfs-0.10.1-ebuild.tar.gz](https://github.com/user-attachments/files/17099720/dwarfs-0.10.1-ebuild.tar.gz)

**Comment by RarogCmex** [comment]
This is finally submitted!
https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=0231b7d21224c2a37ea7049d2283da6e326ed688
I had to make a few changes. For example, the current recomendation for ebuilds is to always build documentation without asking for "use man" or "use doc".
One test is not actually working in my system (dwarfsextract_test.perfmon), I think it's because of sandbox or it might be that I didn't configure all prerequisitions.
Full diff:
```
$ diff dwarfs-0.10.1.ebuild dwarfs-0.10.1_old.ebuild
15c15
< IUSE="+jemalloc test +tools +fuse +perfmon flac ricepp stacktrace"
---
> IUSE="+jemalloc test man +tools fuse doc perfmon flac ricepp stacktrace"
72,73c72,73
<               -DWITH_MAN_PAGES=ON
<               -DWITH_MAN_OPTION=ON
---
>               -DWITH_MAN_PAGES=$(usex doc ON OFF)
>               -DWITH_MAN_OPTION=$(usex man ON OFF)
89,93d88
<       local CMAKE_SKIP_TESTS=(
<               # Perfmon is not working within sandbox
<               dwarfsextract_test.perfmon
<       )
< 
99a95
>               if use man ; then
100a97
>               elif use doc ; then
101a99
>               else
102a101
>               fi
104a104
>               if use man ; then
105a106
>               elif use doc ; then
106a108
>               else
107a110
>               fi

```

**Comment by mhx** [comment]
> One test is not actually working in my system (dwarfsextract_test.perfmon), I think it's because of sandbox or it might be that I didn't configure all prerequisitions.

Can you post the output of the failing test? It works fine for me in the sandbox and I don't know why it wouldn't.

**Comment by mhx** [comment]
> > One test is not actually working in my system (dwarfsextract_test.perfmon), I think it's because of sandbox or it might be that I didn't configure all prerequisitions.
> 
> Can you post the output of the failing test? It works fine for me in the sandbox and I don't know why it wouldn't.

I'll close this for now. Please open a new issue if failing tests are still a problem.
