### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by LargePrime** [mhx/dwarfs#238]
parallel-hashmap-1.3.12/tests/btree_test.cc:844:55:   required from ‘void phmap::priv::{anonymous}::MultiMapTest() [with K = std::__cxx11::basic_string<char>; int N = 256]’
  844 |         BtreeMultiTest<BtreeMMap, std::multimap<K, K>>();
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/parallel-hashmap-1.3.12/tests/btree_test.cc:855:61:   required from here
  855 |     TEST(Btree, multimap_string) { MultiMapTest<std::string>(); }
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~^~
/parallel-hashmap-1.3.12/tests/btree_test.cc:633:39: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  633 |             GTEST_FLAG_GET(random_seed));
      |                                       ^
      |                                       GTEST_FLAG
/parallel-hashmap-1.3.12/tests/btree_test.cc: In instantiation of ‘void phmap::priv::{anonymous}::BtreeMultiTest() [with T = phmap::btree_multimap<std::pair<int, int>, std::pair<int, int>, phmap::Less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >; C = std::multimap<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >]’:
/parallel-hashmap-1.3.12/tests/btree_test.cc:844:55:   required from ‘void phmap::priv::{anonymous}::MultiMapTest() [with K = std::pair<int, int>; int N = 256]’
  844 |         BtreeMultiTest<BtreeMMap, std::multimap<K, K>>();
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/parallel-hashmap-1.3.12/tests/btree_test.cc:856:67:   required from here
  856 |     TEST(Btree, multimap_pair) { MultiMapTest<std::pair<int, int>>(); }
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/parallel-hashmap-1.3.12/tests/btree_test.cc:633:39: error: ‘GTEST_FLAG_GET’ was not declared in this scope; did you mean ‘GTEST_FLAG’?
  633 |             GTEST_FLAG_GET(random_seed));
      |                                       ^
      |                                       GTEST_FLAG
make[2]: *** [CMakeFiles/test_btree.dir/build.make:76: CMakeFiles/test_btree.dir/tests/btree_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:531: CMakeFiles/test_btree.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by mhx** [comment]
Shouldn't this be reported to https://github.com/greg7mdp/parallel-hashmap/?

**Comment by LargePrime** [comment]
done, thanks
https://github.com/greg7mdp/parallel-hashmap/issues/249

**Comment by greg7mdp** [comment]
Why are you building the `parallel-hashmap` tests?

**Comment by mhx** [comment]
> Why are you building the `parallel-hashmap` tests?

Are you asking me or @LargePrime? :)

As for this project (dwarfs), I'm not building these tests, at least not intentionally.

I *think* @LargePrime was trying to build dwarfs using the Arch package and this package pulled in the parallel-hashmap package as a dependency. Maybe the package manager was configured to build tests? I'm just guessing, though.

**Comment by greg7mdp** [comment]
> Are you asking me or @LargePrime? :)

I guess I'm asking @LargePrime :-).

The issue seems to be that for some reason, it is trying to build the `parallel-hashmap` tests (failing here is `parallel-hashmap-1.3.12/tests/btree_test.cc`) which depend on google test. 

Normally this shouldn't happen unless cmake is invoked directly in the phmap directory. However this can also be prevented by passing `-DPHMAP_MASTER_PROJECT=off` to `cmake`.

**Comment by LargePrime** [comment]
just an arch user. I clone and build dwarfs and I get this error.
