### ISSUE TITLE
some targets install to lib even when CMAKE_INSTALL_LIBDIR is set to lib64

### ISSUE THREAD

**Issue by silentnoodlemaster** [mhx/dwarfs#240]
as title says, these are the files

/usr/lib/libdwarfs_common.so
/usr/lib/libdwarfs_common.so.0.10.1
/usr/lib/libdwarfs_reader.so
/usr/lib/libdwarfs_reader.so.0.10.1
/usr/lib/libdwarfs_writer.so
/usr/lib/libdwarfs_writer.so.0.10.1
/usr/lib/libdwarfs_extractor.so
/usr/lib/libdwarfs_extractor.so.0.10.1
/usr/lib/libdwarfs_rewrite.so
/usr/lib/libdwarfs_rewrite.so.0.10.1

**Comment by silentnoodlemaster** [comment]
also these:

   /usr/lib/debug/usr/lib/libdwarfs_common.so.0.10.1-0.10.1-1.fc40.x86_64.debug
   /usr/lib/debug/usr/lib/libdwarfs_extractor.so.0.10.1-0.10.1-1.fc40.x86_64.debug
   /usr/lib/debug/usr/lib/libdwarfs_reader.so.0.10.1-0.10.1-1.fc40.x86_64.debug
   /usr/lib/debug/usr/lib/libdwarfs_rewrite.so.0.10.1-0.10.1-1.fc40.x86_64.debug
   /usr/lib/debug/usr/lib/libdwarfs_writer.so.0.10.1-0.10.1-1.fc40.x86_64.debug
   
idk what they are tho

**Comment by mhx** [comment]
Sorry for the late reply. This should be fixed by the above commit.

The `.debug` files are files containing debug symbols. These are likely being created by the packaging toolchain during installation.
