### ISSUE TITLE
FUSE graceful exit on initialization error

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#27]
I've tried to use `-o mlock=must` and (as it should) failed due to the per user limits.

However the `dwarfs` (both v2 and v3 FUSE drivers) aborted with an exception, and failed to properly unmount the file-system.

I think the FUSE driver first should try to execute all initialization steps, and if all succeed, only then to try to mount the filesystem.

**Comment by mhx** [comment]
Ah, I just fixed that one along with #26. I did change the error handling quite a bit in the next-release branch and the FUSE driver hadn't (hasn't) gone through all the necessary modifications yet. Fixed by ddf52b2a4490fa7a78d2a1b17298d1fdc7a8d077.
