### ISSUE TITLE
Add rubygen-ronn dependency

### ISSUE THREAD

**Issue by rurban** [mhx/dwarfs#3]
to the README and somehow integrate the `man/Makefile` into cmake.
I had to manually do it, and only then was able to do a `sudo make install`

**Comment by mhx** [comment]
Thanks, I just didn't get around to integrating this with CMake yet. The generated files are included in the release tarball, though, so it's only an issue if you're building directly from the repo.

**Comment by mhx** [comment]
Should be fixed in 6e2a110.

**Comment by rurban** [comment]
Thanks!
