### ISSUE TITLE
Error:variable ‘folly::symbolizer::Symbolizer symbolizer’ has initializer but incomplete type

### ISSUE THREAD

**Issue by RarogCmex** [mhx/dwarfs#31]
I'm trying to create ebuild for 0.3.0 dwarfs version. And here is an error:
/usr/bin/x86_64-pc-linux-gnu-g++ -DDWARFS_HAVE_LIBLZ4 -DDWARFS_HAVE_LIBLZMA -DDWARFS_HAVE_LIBZSTD -DDWARFS_STATIC_BUILD=OFF -DDWARFS_USE_JEMALLOC -DDWARFS_VERSION=\"\" -DFMT_LOCALE -DFMT_SHARED -DGFLAGS_IS_A_DLL=0 -Ddwarfs_EXPORTS -Iinclude -I/usr/include/libiberty -isystem folly -isystem thrift -isystem fbthrift -isystem zstd/lib -isystem xxHash -isystem .  -march=skylake -mtune=skylake -O2 -pipe -mmmx -msse -msse2 -msse3 -mssse3 -mcx16 -msahf -maes -mpclmul -mpopcnt -mabm -mfma -mbmi -msgx -mbmi2 -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mrdseed -mprfchw -madx -mfxsr -mxsave -mxsaveopt -mclflushopt -mxsavec -mxsaves --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -fPIC   -Wall -Wextra -pedantic -pthread -std=c++17 -MD -MT CMakeFiles/dwarfs.dir/src/dwarfs/logger.cpp.o -MF CMakeFiles/dwarfs.dir/src/dwarfs/logger.cpp.o.d -o CMakeFiles/dwarfs.dir/src/dwarfs/logger.cpp.o -c src/dwarfs/logger.cpp
src/dwarfs/logger.cpp: In member function ‘virtual void dwarfs::stream_logger::write(dwarfs::logger::level_type, const string&, const char*, int)’:
src/dwarfs/logger.cpp:102:51: error: variable ‘folly::symbolizer::Symbolizer symbolizer’ has initializer but incomplete type
  102 |       Symbolizer symbolizer(LocationInfoMode::FULL);
      |                                                   ^

**Comment by RarogCmex** [comment]
The complete build.log:
[build.log](https://github.com/mhx/dwarfs/files/5781237/build.log)
emerge --info (for installed dwarfs 0.2.4) https://dpaste.com/GGQPWXQBM
dependency graph (for installed dwarfs 0.2.4) https://dpaste.com/5ENSEEPZZ

**Comment by RarogCmex** [comment]
That issue does not relly to jemalloc. It reproduces regardless.

**Comment by mhx** [comment]
Can you please attach the ebuild? Thanks!

**Comment by RarogCmex** [comment]
[dwarfs-0.3.0.ebuild.txt](https://github.com/mhx/dwarfs/files/5781560/dwarfs-0.3.0.ebuild.txt)

**Comment by mhx** [comment]
I had to make a couple of small tweaks due to having multiple versions of python installed (also `WITH_PYTHON` was set from `jemalloc` USE flag). It's working fine for me, I'll take a closer look later at how your environment is different from mine.

**Comment by mhx** [comment]
Question: why is all this patching necessary in `src_prepare`? I would guess that `cmake_src_prepare` already takes care of properly setting the install prefix for cmake builds?

**Comment by RarogCmex** [comment]
The issues reproduced even if I comment flags in ebuild.
That patches should fix the output directory for /usr/lib (which is /usr/lib64 for me).

**Comment by mhx** [comment]
> That patches should fix the output directory for /usr/lib (which is /usr/lib64 for me).

Shouldn't these symlink to the same directory?

    $ ll /usr/lib* -d
    lrwxrwxrwx 1 root root      5 May 29  2019 /usr/lib -> lib64
    drwxr-xr-x 1 root root  43174 Jan  6 15:13 /usr/lib32
    drwxr-xr-x 1 root root 139052 Jan  7 13:42 /usr/lib64
    drwxr-xr-x 1 root root   1724 Jan  6 12:18 /usr/libexec

**Comment by RarogCmex** [comment]
No more since Gentoo profile 17.1 become stable. Here is the news:
https://www.gentoo.org/support/news-items/2019-06-05-amd64-17-1-profiles-are-now-stable.html

> In the new profiles, the lib->lib64 compatibility symlink is removed.
> 64-bit libraries need to be installed directly to lib64.  /lib
> and /usr/lib become real directories, that are used for cross-arch
> and native non-library packages (gcc, clang) and 32-bit libraries
> on the multilib profile (which improves compatibility with prebuilt x86
> packages).

**Comment by mhx** [comment]
Ah, ok. I've yet to make the switch from 17.0 to 17.1.

**Comment by mhx** [comment]
Given that `gentoo_common_config.cmake` has

    set(CMAKE_INSTALL_LIBDIR lib64 CACHE PATH "Output directory for libraries")

I think there should be an easier way of fixing this.

**Comment by mhx** [comment]
I've got fixes for a couple of issues including this one and also building with Python which wouldn't work. Will make a new release later.

**Comment by mhx** [comment]
A [new release](https://github.com/mhx/dwarfs/releases/tag/v0.3.1) is out that builds fine on my 17.1 profile machine with [dwarfs-0.3.1.ebuild.txt](https://github.com/mhx/dwarfs/files/5783190/dwarfs-0.3.1.ebuild.txt).

Please re-open if you still have problems.

**Comment by RarogCmex** [comment]
> Given that `gentoo_common_config.cmake` has
> 
> ```
> set(CMAKE_INSTALL_LIBDIR lib64 CACHE PATH "Output directory for libraries")
> ```
> 
> I think there should be an easier way of fixing this.

In random profiles there are different paths to main library directory. For example, in arm (not arm64) arch it should be /usr/lib. So $(get_libdir) more reliable I think.

**Comment by RarogCmex** [comment]
Ok, final ebuild is sended to dev branch of Gentoo GURU project. After some time it will be pushed to master so anyone will be able use it as use any GURU ebuilds.
