### ISSUE TITLE
Possibility to build atop exact system libraries (unbundle its)

### ISSUE THREAD

**Issue by RarogCmex** [mhx/dwarfs#34]
At this moment dwarfs use own bundled libraries. That's bad practice if we are building in source-based system like gentoo: I've just found off that revdep-rebuild (utility which checks if all package are consistent) triggers to dwarfs:
RarogCmexDell ~ # revdep-rebuild --pretend
 * This is the new python coded version
 * Please report any bugs found using it.
 * The original revdep-rebuild script is installed as revdep-rebuild.sh
 * Please file bugs at: https://bugs.gentoo.org/
 * Collecting system binaries and libraries
 * Checking dynamic linking consistency
 * Assign files to packages

emerge --pretend --oneshot --complete-graph=y sys-fs/dwarfs:0

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] sys-fs/dwarfs-0.3.1-r2 

So it'll be good to unbound at least xxhash and zstd sources (at this moment it used in cmake, I'm not able to patch cmake because I don't know it) like previous 0.2.4 version which does not relly on bundled libraries.

The ebuild to play around in GURU repository:
eselect repository enable guru

**Comment by mhx** [comment]
This will be fixed in the next release. You can then specify `-DPREFER_SYSTEM_ZSTD=1` and `-DPREFER_SYSTEM_XXHASH=1` to use the system versions *if* they are available.

**Comment by mhx** [comment]
Fixed in v0.4.0.
