### ISSUE TITLE
libdwarfs.so: undefined reference to `archive_format'

### ISSUE THREAD

**Issue by RarogCmex** [mhx/dwarfs#36]
Looks like another dependency issue. However, I don't understand C++ enought
Ebuild to reproduce issue:
[dwarfs-0.4.0.ebuild.txt](https://github.com/mhx/dwarfs/files/6097353/dwarfs-0.4.0.ebuild.txt)
Also additional build flags (see ebuild):
-DPREFER_SYSTEM_ZSTD=1
-DPREFER_SYSTEM_XXHASH=1
-DWITH_LEGACY_FUSE=0

[environment.txt](https://github.com/mhx/dwarfs/files/6097341/environment.txt)
[emerge--info.txt](https://github.com/mhx/dwarfs/files/6097343/emerge--info.txt)

The complete build log:
[build.log.txt](https://github.com/mhx/dwarfs/files/6097344/build.log.txt)

**Comment by RarogCmex** [comment]
Detailed dependency list:
[dependencies.txt](https://github.com/mhx/dwarfs/files/6097374/dependencies.txt)

**Comment by mhx** [comment]
This is likely a missing dependency on `app-arch/libarchive`.

**Comment by mhx** [comment]
Ooops, wrong button. Let me know if this works!

**Comment by RarogCmex** [comment]
It did not:
[build.log](https://github.com/mhx/dwarfs/files/6099679/build.log)

Libarchive is installed in my system, but not listed (thanks for adding it to dependencies):
[I] app-arch/libarchive
     Available versions:  3.5.1(0/13) {acl blake2 +bzip2 +e2fsprogs expat +iconv libressl lz4 +lzma lzo nettle static-libs +threads xattr +zlib zstd ABI_MIPS="n32 n64 o32" ABI_S390="32 64" ABI_X86="32 64 x32" KERNEL="linux"}
     Installed versions:  3.5.1(0/13)(15:31:21 02/11/21)(acl bzip2 e2fsprogs iconv lz4 lzma lzo threads xattr zlib zstd -blake2 -expat -libressl -nettle -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="32 64 -x32" KERNEL="linux")
     Homepage:            https://www.libarchive.org/
     Description:         Multi-format archive and compression library

**Comment by mhx** [comment]
Can you try adding `eapply "${FILESDIR}/link.patch"` to `src_prepare` with this [link.patch](https://gist.githubusercontent.com/mhx/e1d140048378a231fbf3a72588b4f47b/raw/3b1ce07cb608e6e2edf9cc3b39d6c6d9c3c2aae3/link.patch)?

**Comment by RarogCmex** [comment]
It works. Thank you. I'll further test it out in my server, then push it to GURU.

**Comment by RarogCmex** [comment]
It seems issue can be closed. If something happens I'll reopen it.
