### ISSUE TITLE
Ability to mount images by offset

### ISSUE THREAD

**Issue by Kron4ek** [mhx/dwarfs#38]
Would be useful (for the situations when a dwarfs image is a part of another file) to have an ability to mount dwarfs images by offset. Like:
```
dwarfs -o offset=123 file mountpoint
```

**Comment by Phantop** [comment]
I'd also just like to add that the option should be added to `dwarfsextract`, if this is implemented. 

This is incredibly useful for appimage-like usage. I've personally been using dwarfs images inside an appimage with no compression to create makeshift dwarfs-based appimages as a workaround for the lack of this option (script for that [here](https://github.com/Phantop/dotfiles/blob/main/.local/bin/appdwarf), which works out rather well with many larger programs. Having a less hacky way to run scripts with dwarfs files would be really appreciated.

**Comment by mhx** [comment]
Didn't think of this use case before, but it seems useful and it's easy enough to add. This is now implemented in [next-release](https://github.com/mhx/dwarfs/tree/next-release) branch and will be part of v0.5.0 (due hopefully before easter).

    $ cat ../@compat/format.sh test.dwarfs >x.dwarfs 
    $ dwarfsck x.dwarfs 
    DwarFS version 2.3 [2] at offset 94
    created by: libdwarfs v0.4.1-104-gb7ec25b-dirty on branch next-release
    created on: 2021-03-27 23:47:34

Instead of an explicit offset in bytes, you can also specify `auto` and the offset will be determined automatically (assuming there's only a single DwarFS image in the file). `--image-offset=auto` is the default for both `dwarfsck` and `dwarfsextract` (that's why it's unspecified in the above `dwarfsck` invocation). For `dwarfs`, you can explicitly specify `-o offset=auto`.

**Comment by Phantop** [comment]
> For `dwarfs`, you can explicitly specify `-o offset=auto`.

Why exactly is this not the default?

**Comment by mhx** [comment]
> > For `dwarfs`, you can explicitly specify `-o offset=auto`.
> 
> Why exactly is this not the default?

It just felt a little bit safer for the fuse driver. Just gut feeling. The tools are run interactively, but the fuse driver may get run in the background and I wouldn't want it to do funny things on its own.

Maybe I'll change my mind before the release. :-)

**Comment by Phantop** [comment]
As a little extra that would go well with this, would it be possible to allow for `mkdwarf` to create a dwarfs image and directly append it to another file to reduce the amount of data that would need to be written and thus  save on writes and time?

**Comment by mhx** [comment]
> As a little extra that would go well with this, would it be possible to allow for `mkdwarfs` to create a dwarfs image directly appended to another file to reduce the amount of data that would need to be written and thus save on writes and time (preventing the need to `cat` any files together)?

That actually also crossed my mind. Plus the ability to copy that data when rewriting.

**Comment by Kron4ek** [comment]
@mhx Thank you, will try to compile and test.

**Comment by mhx** [comment]
@Phantop, I've added a few more things. You can now supply a custom header with `mkdwarfs`:

    $ mkdwarfs -i dir -o x.dwarfs --header stuff.sh

Or inline with process substitution:

    $ mkdwarfs -i dir -o x.dwarfs --header <(echo "Hello!")

You can use `dwarfsck` to actually look at the header:

    $ dwarfsck x.dwarfs -H
    Hello!

You can add a header to an existing filesystem, or replace an existing header (though only by rewriting):

    $ mkdwarfs -i x.dwarfs -o y.dwarfs --recompress=none --header=stuff.sh

Or you can remove the header (again, only by rewriting):

    $ mkdwarfs -i x.dwarfs -o y.dwarfs --recompress=none --remove-header

**Comment by Kron4ek** [comment]
Seems to work fine for me, haven't found any issues. Auto offset also works fine.

**Comment by mhx** [comment]
I've just released v0.5.0.

**Comment by RarogCmex** [comment]
Dwarfs for linux games? It would be nice.

**Comment by Phantop** [comment]
> Dwarfs for linux games? It would be nice.

I've actually been doing this. Wrote a [small script](https://github.com/Phantop/dotfiles/blob/main/.local/bin/appdwarf) that takes an AppImage folder and compresses it via dwarfs. It expects a `dwarfs` binary in PATH but it works out well.
