### ISSUE TITLE
Speeding up mount times without sacrificing compression

### ISSUE THREAD

**Issue by naphthasl** [mhx/dwarfs#48]
So, I've been using DwarFS for a while now, and I'm loving it - I've had success with compressing my huge multi-terabyte backups with version 0.5.5, and all is well, except for one kind of massive problem: The mount times.... are atrocious!

I have a directory containing 1.5 TiB worth of separate DwarFS archives, but I'm going to focus on just one of them specifically for this example, `3TBDRV-PartC-05-Jun-2021.dwarfs`, which is 129.1 GiB large, and 191.5 GiB uncompressed, with 452854 files. And oh boy, look at this:

```
I 17:17:22.057967 file system initialized [4460s]
```

That took over an *hour* to mount! (Ryzen 5 3600, 64 GB of RAM, DwarFS archive was stored on a Toshiba PC P300 3 TB hard disk)

In fact, this kind of extremely slow mounting time was consistent with all of the other archives too, even some stored on other drives:

```
I 16:03:03.018227 file system initialized [709.9ms]
I 16:03:03.849098 file system initialized [1.53s]
I 16:03:33.590178 file system initialized [31.27s]
I 16:03:55.387080 file system initialized [53.07s]
I 16:04:05.065723 file system initialized [62.75s]
I 16:04:29.313615 file system initialized [87s]
I 16:04:31.894768 file system initialized [89.57s]
I 16:04:37.869410 file system initialized [95.55s]
I 16:04:47.800754 file system initialized [105.5s]
I 16:07:38.591166 file system initialized [276.3s]
I 16:10:38.510593 file system initialized [456.2s]
I 16:11:29.503998 file system initialized [507.2s]
I 16:13:05.969340 file system initialized [603.7s]
I 16:26:54.248746 file system initialized [1432s]
I 16:27:27.300756 file system initialized [1465s]
I 16:30:56.814199 file system initialized [1675s]
I 16:45:29.011485 file system initialized [2547s]
I 16:45:40.813002 file system initialized [2558s]
I 16:46:33.700585 file system initialized [2611s]
I 17:12:16.627675 file system initialized [4154s]
I 17:13:47.702170 file system initialized [4245s]
I 17:17:22.057967 file system initialized [4460s]
I 17:27:46.640421 file system initialized [5084s]
```

I found this in the `mkdwarfs` documentation:

> The metadata has been optimized for very little redundancy and leaving it uncompressed, the default for all levels below 7, has the benefit that it can be mapped to memory and used directly. This improves mount time for large file systems compared to e.g. an lzma compressed metadata block. If you don't care about mount time, you can safely choose lzma compression here, as the data will only have to be decompressed once when mounting the image.

If I'm reading this right, for all compression levels above or equal to 7, DwarFS is taking all of the metadata and decompressing it all at once at mount time. Is there any way this could be improved? Decompressing everything at once seems to be kind of a bad idea. I don't want to outright disable metadata compression, as there's kind of a lot of it and I get the feeling it would benefit from being compressed, but these mount times really are excessive - it actually kind of makes SquashFS preferable to DwarFS for the goal of having a compressed read-only filesystem that mounts quickly and is accessible quickly.

I'll admit I don't know much about DwarFS' actual internals, but how about this: what if the metadata was compressed in multiple separate chunks/blocks of a fixed size, and only the blocks that are actually needed get decompressed at any given time? Perhaps this could be made optional, or even the default at level 7 while 8 and 9 could compress the metadata all at once?

I'm not entirely sure on the specifics of how these mount times could be improved, but I feel like if level 7 is going to be the default then it should at least try to optimize the metadata for fast access (or at least, faster than *this*) somehow, without completely disabling compression, as compressing the metadata probably helps a lot with DwarFS' excellent space efficiency.

Or maybe compressing the metadata isn't worth it? The statement "The metadata has been optimized for very little redundancy" in the documentation seems to imply that compressing the metadata doesn't really help that much, are there any comparisons we can make between uncompressed and compressed metadata? How worthwhile even *is* compressing it? Should it continue to be enabled by default?

**Comment by naphthasl** [comment]
Oh.. uh.. right, is it possible to speed up the mount time of existing DwarFS volumes without re-compressing them? I've just discovered I need to remount all of them... and I need to wait another 2 hours for them to mount...

**Comment by mhx** [comment]
Hey, thanks for the detailed report!

I *think* you're actually seeing a completely different issue here. The mount times are likely not bad because of the metadata (452854 files isn't enough to cause an excessively large metadata block), but because the driver performs an integrity check of all filesystem blocks when mounting. This means it will have to read *the whole filesystem* once. I do realize this is something you likely don't want to do for filesystem images that are hundreds of gigabytes in size and potentially stored on spinning disks.

So don't worry about metadata (at least not yet). I would assume your metadata block is tiny compared to the actual file data. You can actually check this using `dwarfsck`, which will show a detailed breakdown of the metadata block's memory usage.

Unfortunately, there's currently no way to disable the integrity check, but this is trivial to add and I'll try to quickly get out a release that adds support for disabling the check.

**Comment by mhx** [comment]
That being said, I've got a 12 GiB filesystem of 14,000,000 files with an uncompressed size of 198 GiB here that mounts in about 260 milliseconds, and this is likely why I never even considered the integrity check to be an issue. (But this is still an order of magnitude less than the size of your image, and mine is stored on a PCIe SSD.)

**Comment by mhx** [comment]
In any case, the good news is that you won't have to rebuild your filesystems, and mounting with disabled integrity checks will definitely be much faster. :)

**Comment by Phantop** [comment]
Just going to pop in to note that I have a 31 GB image (51 GB uncompressed) on a 5400 RPM hard drive over USB 2 that mounted in about 30 seconds. No idea if that's useful information since it's substantially smaller than what @naphthasl was trying to mount but do agree that bypassing integrity checks for larger images (or images on slower drives) would be convenient.

**Comment by naphthasl** [comment]
Ah okay, this is almost certainly the integrity check slowing everything down then - Checking GNOME System Monitor, I can definitely see that every `dwarfs` process is re-reading the entire filesystem once. *Ouch.*

I was thinking though, maybe the whole-filesystem integrity check could be moved to the `dwarfsck` tool and perhaps `dwarfs` could verify the integrity of individual files on read or something instead? I feel like it's a little unusual to check the integrity of the entire filesystem every single mount, especially by default. Then again, it is certainly worth it to be informed when the filesystem is damaged as soon as possible, I suppose.

**Comment by mhx** [comment]
> Just going to pop in to note that I have a 31 GB image (51 GB uncompressed) on a 5400 RPM hard drive over USB 2 that mounted in about 30 seconds. No idea if that's useful information since it's substantially smaller than what @naphthasl was trying to mount but do agree that bypassing integrity checks for larger images (or images on slower drives) would be convenient.

That sounds surprisingly fast. Did you create that image with a pre-0.3.0 release by any chance? The old filesystem image format didn't support integrity checks at all.

**Comment by Phantop** [comment]
> > Just going to pop in to note that I have a 31 GB image (51 GB uncompressed) on a 5400 RPM hard drive over USB 2 that mounted in about 30 seconds. No idea if that's useful information since it's substantially smaller than what @naphthasl was trying to mount but do agree that bypassing integrity checks for larger images (or images on slower drives) would be convenient.
> 
> That sounds surprisingly fast. Did you create that image with a pre-0.3.0 release by any chance? The old filesystem image format didn't support integrity checks at all.

Nah this was with one of the lastest releases, as I made the image sometime last month. But yeah I was rather surprised that it mounted as fast as it did.

**Comment by mhx** [comment]
> I was thinking though, maybe the whole-filesystem integrity check could be moved to the `dwarfsck` tool and perhaps `dwarfs` could verify the integrity of individual files on read or something instead? I feel like it's a little unusual to check the integrity of the entire filesystem every single mount, especially by default. Then again, it is certainly worth it to be informed when the filesystem is damaged as soon as possible, I suppose.

Yeah, now that the issue has popped up, it seems like a strange decision to me, too. :)

So yes, this will likely be turned off by default in the future. Instead, I'll perform the check only when the block actually needs to be decompressed.

**Comment by mhx** [comment]
Ok, this is a bit embarrassing, but... @Phantop's comment made me take another look at the code, and after reading it wrong the first time I looked at it earlier, I found that it's already implemented in exactly the way that I was envisioning for the next release...

This definitely explains why @Phantop's 31 GB image mounts in 30 seconds over USB.

However, I'm shocked that @naphthasl's image takes an hour to mount. This doesn't make any sense to me.

I'm still confident that it's unrelated to metadata compression.

@naphthasl, a couple of questions:

- Can you confirm that the `dwarfs` processes aren't consuming CPU resources while mounting?
- Are you mounting multiple images at the same time? Or are they mounted sequentially?

So, my best guess right now is the following:

I'm assuming you've built the 192 GiB image with 16 MiB block size, which means the filesystem image will probably consist of a bit more than 10,000 blocks. Now, upon mounting, `dwarfs` will have to build an index of these blocks. This works by traversing the block headers (each header contains the block length and thus a "pointer" to the next block). The headers are relatively short (64 bytes, see [the format description](https://github.com/mhx/dwarfs/blob/main/doc/dwarfs-format.md)), however, the `dwarfs` process will have to read these small chunks from across the whole image. With 10,000 blocks, this means the drive will likely have to make (at least) 10,000 non-sequential read accesses. Assuming from the time stamps that you're mounting the images in parallel, there are likely multiple processes trying to make a lot of non-sequential reads. (It's unlikely that mounting the images sequentially will improve the overall mount time, but it'll probably bring down the time each individual mount takes.)

I've tried my 12 GiB image (~3,000 blocks) on a RAID6 of 7200rpm disks and mount time increased to 20 seconds, so roughly 7ms per seek, which sounds quite reasonable.

So I can see that this isn't ideal for your use case. The intuitive solution would be to add an index block at the very end of the filesystem image and ensure this index can be accessed with a single seek. Such an index block could also be added to old images. However, it would add a certain amount of redundancy, though likely negligible. I'll spend a bit more time thinking about this.

**Comment by naphthasl** [comment]
I tried mounting both sequentially and in parallel - when mounting sequentially, the `dwarfs` process would always consume 100% of a single core, and when mounting in parallel, this would increase somewhat to saturating just under two cores.

This is rather confusing though, because the reads don't look very non-sequential to me - if I mount sequentially, GNOME System Monitor describes the `dwarfs` process as reading at about 130 MiB/sec, which definitely sounds like the read throughout of the drive, and it states that the "Total Read" figure is around the same size as the whole archive when it's nearly finished...

This is all happening on 0.5.5, so if there's no global integrity check doing this, then... this is very confusing.

**Comment by mhx** [comment]
> I tried mounting both sequentially and in parallel - when mounting sequentially, the dwarfs process would always consume 100% of a single core, and when mounting in parallel, this would increase somewhat to saturating just under two cores.

Whoa. Are you certain this is CPU *user* time?

> This is rather confusing though, because the reads don't look very non-sequential to me - if I mount sequentially, GNOME System Monitor describes the dwarfs process as reading at about 130 MiB/sec, which definitely sounds like the read throughout of the drive, and it states that the "Total Read" figure is around the same size as the whole archive when it's nearly finished...

I know what the issue is: readahead.

Linux defaults to read ahead several pages when you access an `mmap`ed file (or when you do a plain `read` call). "several" can apparently be "plenty" as I've just found out: in my 12 GiB image, almost the entire image data is read when building the index (so that's 600 MiB/s, which sounds about right for the RAID6). I've quickly built a version of `dwarfs` that will `madvise(MADV_RANDOM)` on the entire image, which (at least on Linux) will completely disable the readahead. This reduces the actual amount of data being read from disk to a few dozen MiBs, which sounds about right given that the granularity at which data is read is one page size.

**Comment by naphthasl** [comment]
> Whoa. Are you certain this is CPU user time?

I was just looking at the CPU usage graph in GNOME system monitor, I'm not certain on whether this was user time or system time.

> I've quickly built a version of `dwarfs` that will `madvise(MADV_RANDOM)` on the entire image, which (at least on Linux) will completely disable the readahead.

Is there any way I can disable readahead for myself before the next version of DwarFS? Like a command or environment variable or something?

**Comment by mhx** [comment]
> Is there any way I can disable readahead for myself before the next version of DwarFS? Like a command or environment variable or something?

You can try to tweak the readahead setting per block device using:

    blockdev --setra <blocks> <device>

The readahead is specified in number of 512-byte blocks and for my RAID6 it turns out to be set to a whopping 10240 blocks (i.e. 5 MiB), which explains why it read the whole file. :)

I'd use this carefully, though. While it may help speed up the index-building step, it'll likely make every other operation *significantly* slower. E.g. loading the metadata (500 MiB) with readahead disabled was more than 10 times slower than with readahead.

**Comment by naphthasl** [comment]
Hmm, setting both `--setra` and `--setfra` to 1 instead of 256 (the default) seemed to make the extreme mount times even worse for me.

**Comment by mhx** [comment]
> Hmm, setting both (or either) `--setra` and `--setfra` to 1 instead of 256 (the default) seemed to make the extreme mount times even worse for me.

Did you see any difference in the amount of data read by the process?

> I've read that Btrfs makes extensive use of memory caching, could this be part of the issue? And if so, do you think `madvise(MADV_RANDOM)` would cooperate with Btrfs?

I honestly have no idea. Neither `blockdev` nor `MADV_RANDOM` are going to be a solution. The solution will be to simply avoid scanning through the whole file upon mounting by using an index. (Luckily, this is more straightforward than solving the SIGBUS issue...)

**Comment by naphthasl** [comment]
> Did you see any difference in the amount of data read by the process?

Nope. System Monitor reported it reading roughly exactly the same amount as before.

**Comment by mhx** [comment]
> Nope. System Monitor reported it reading roughly exactly the same amount as before.

In that case, I assume btrfs is doing its own readahead.
