### ISSUE TITLE
Extra non-flag arguments are ignored (instead of issuing a warning or error)

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#5]
At least for `mkdwarfs` if one sets an extra argument like for example `mkdwarfs -i ... -o ... Z` (i.e. the `Z`) it just ignores it without failing.

Although this is not a major issue, especially in case of wrapper scripts and automation tools, a small bug in the user's code could fail for example to prepend `-S` before the user input, and thus that input would just be silently ignored by the tool.

**Comment by mhx** [comment]
Oh wow, thanks for noticing that. I'll take a look!

**Comment by mhx** [comment]
Fixed for `mkdwarfs` in 774ad7c.
