### ISSUE TITLE
dwarfsextract aborts instead of skipping when corrupt files are encountered

### ISSUE THREAD

**Issue by ghost** [mhx/dwarfs#51]
```
Extracting 2b2tca.dwarfs...
E 03:24:38.703663 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714209 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714279 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714363 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714432 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714515 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714588 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714693 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714805 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.714884 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715012 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715088 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715217 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715300 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715390 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715468 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715540 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715607 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715676 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715740 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715820 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715897 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.715975 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716048 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716123 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716199 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716266 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716341 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716408 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716484 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716555 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716654 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716719 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716794 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716876 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.716950 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717018 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717081 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717174 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717247 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717354 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717426 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717502 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717570 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717641 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717710 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717773 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717842 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717909 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.717983 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718189 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718259 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718332 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718401 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718487 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718557 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718631 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718690 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718769 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718831 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718902 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.718977 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
E 03:24:38.719046 dwarfs::runtime_error: LZMA: decompression failed (data is corrupt)
I 03:24:41.164877 blocks created: 1298
I 03:24:41.164926 blocks evicted: 1290
I 03:24:41.164955 request sets merged: 9576
I 03:24:41.164983 total requests: 150010
I 03:24:41.165008 active hits (fast): 22247
I 03:24:41.165033 active hits (slow): 122699
I 03:24:41.165063 cache hits (fast): 3184
I 03:24:41.165090 cache hits (slow): 582
I 03:24:41.165117 total bytes decompressed: 87106428928
I 03:24:41.180369 average block decompression: 100.0%
I 03:24:41.180425 fast hit rate: 16.953%
I 03:24:41.180464 slow hit rate: 82.182%
I 03:24:41.180502 miss rate: 0.865%
dwarfs::runtime_error: extraction aborted
```

Mounts just fine with `dwarfs`, and almost every file reads just fine - however, as soon as `dwarfsextract` encounters invalid data, it seems to just completely bail out, unlike `dwarfs`. I would use `dwarfs` to extract instead, but the performance seems to be orders of magnitude slower.

I think the expected behavior ought to be printing a warning and skipping the file instead.

PS: `dwarfsextract` doesn't seem to give realtime progress updates like `mkdwarfs` does either :(

**Comment by mhx** [comment]
This should be easy to change. As I said, actual recovery from corrupted images hasn't gotten much attention yet in the tools.

> I would use `dwarfs` to extract instead, but the performance seems to be orders of magnitude slower.

That is quite expectedly the case. `dwarfsextract` ensures files are extracted in the order they're stored in the image.

> PS: `dwarfsextract` doesn't seem to give realtime progress updates like `mkdwarfs` does either :(

Yup, that's partly lack of time to properly polish the tools, partly because at least for me `dwarfsextract` typically does its job in a matter of seconds.

**Comment by naphthasl** [comment]
I've also discovered that running `dwarfsextract` on some of the corrupted filesystems eventually causes a memory leak and triggers the OOM killer instead of simply reporting an error and aborting as it did for that particular filesystem. Is there any way I can collect more information on this for you? As far as I can tell, the best I can do is `echo 1 > /proc/sys/vm/oom_dump_tasks`, which apparently causes the kernel to generate core dumps for every single currently running process whenever a process is OOM killed, which I don't particularly think would be a good idea.

**Comment by mhx** [comment]
> I've also discovered that running dwarfsextract on some of the corrupted filesystems eventually causes a memory leak and triggers the OOM killer instead of simply reporting an error and aborting as it did for that particular filesystem.

Mmmh, odd. Are there any huge files in the image, like files that would have a hard time fitting into RAM completely? This might not be a memory leak, but rather the process using a lot of memory (that it would eventually free, but instead it got OOM-killed).

> Is there any way I can collect more information on this for you?

Don't worry about it for now. I'll try to work through some test data here when I get around to looking into this in more detail.

**Comment by naphthasl** [comment]
> Mmmh, odd. Are there any huge files in the image, like files that would have a hard time fitting into RAM completely? This might not be a memory leak, but rather the process using a lot of memory (that it would eventually free, but instead it got OOM-killed).

Ah, if you mean singular files that just so happen to be above 128 GiB in size (uncompressed, at least)... yep. There are a lot of those. I worried that it might be something like that, but I guess the potential for the corrupted data to have broken something in `dwarfsextract` must've lead me to refer to this as a memory leak a little prematurely.

If large files is the issue, then that'd definitely make a lot of sense - all of the DwarFS filesystems that got `dwarfsextract` OOM-killed were the largest filesystems with some of the largest files. One of them didn't actually even show any signs of being corrupt (as in, it didn't trigger any I/O errors from the actual drive), but neither did `2b2tca.dwarfs`, which turned out to be corrupt regardless of whether or not the drive itself produced I/O errors for it, so I'm kind of just assuming that *everything* is at least slightly corrupt at this point just in case.

**Comment by mhx** [comment]
> > Mmmh, odd. Are there any huge files in the image, like files that would have a hard time fitting into RAM completely? This might not be a memory leak, but rather the process using a lot of memory (that it would eventually free, but instead it got OOM-killed).
> 
> Ah, if you mean singular files that just so happen to be above 128 GiB in size (uncompressed, at least)... yep. There are a lot of those. I worried that it might be something like that, but I guess the potential for the corrupted data to have broken something in `dwarfsextract` must've lead me to refer to this as a memory leak a little prematurely.
> 
> If large files is the issue, then that'd definitely make a lot of sense - all of the DwarFS filesystems that got `dwarfsextract` OOM-killed were the largest filesystems with some of the largest files.

Ah, this part of the problem is likely solved by fixing #104 with the 0.6.2 release. Could you perhaps give this a try?

**Comment by mhx** [comment]
I've added two new options to `dwarfsextract` that should make it possible to extract data from corrupted file system images.

**Comment by mhx** [comment]
Please check out the v0.7.0-RC1 release candidate: https://github.com/mhx/dwarfs/releases/tag/v0.7.0-RC1
