### ISSUE TITLE
Latest dwarfs release (0.5.5) fails to build on latest Arch Linux because of gcc11

### ISSUE THREAD

**Issue by bionade24** [mhx/dwarfs#52]
626b8c0f6aa2101802a93653bbd18651999caaf1 has to be in a release to let it work again.

**Comment by mhx** [comment]
Thanks, I'll push a new release soon!

**Comment by mhx** [comment]
Fixed in [v0.5.6](https://github.com/mhx/dwarfs/releases/tag/v0.5.6).
