### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by iasatan** [mhx/dwarfs#65]
It took me 20 minutes to install everything for the project on one of my computer as a test.
I do not want to do it again.

A simple docker container with a volume would solve all of the problems.
Also a seperate project for the mounting part

**Comment by Phantop** [comment]
There are static binaries on the releases page that should work on any distribution with FUSE installed and available. I've used them successfully on distributions based on both musl and glibc, as well as on WSL.

**Comment by mhx** [comment]
Pretty much what @Phantop said.

My experience with docker is limited, but given there are statically linked binaries readily available, it seems to me a bit like using a sledgehammer to crack a nut.
