### ISSUE TITLE
dwarfs throws link errors on arm64

### ISSUE THREAD

**Issue by bdnbje** [mhx/dwarfs#66]
make[1]: *** [CMakeFiles/Makefile2:459: CMakeFiles/dwarfsextract.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: metadata_v2.cpp:(.text._ZN6dwarfs9metadata_INS_19debug_logger_policyEEC2ERNS_6loggerEN5folly5RangeIPKhEES9_RKNS_16metadata_optionsEib[_ZN6dwarfs9metadata_INS_19debug_logger_policyEEC2ERNS_6loggerEN5folly5RangeIPKhEES9_RKNS_16metadata_optionsEib]+0x65c): undefined reference to `fmt::v8::vformat[abi:cxx11](fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
/usr/bin/ld: metadata_v2.cpp:(.text._ZN6dwarfs9metadata_INS_19debug_logger_policyEEC2ERNS_6loggerEN5folly5RangeIPKhEES9_RKNS_16metadata_optionsEib[_ZN6dwarfs9metadata_INS_19debug_logger_policyEEC2ERNS_6loggerEN5folly5RangeIPKhEES9_RKNS_16metadata_optionsEib]+0x6d0): undefined reference to `fmt::v8::vformat[abi:cxx11](fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
/usr/bin/ld: libdwarfs.a(metadata_v2.cpp.o):metadata_v2.cpp:(.text._ZNK6dwarfs9metadata_INS_19debug_logger_policyEE4dumpERSoiRKNS_15filesystem_infoERKSt8functionIFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjEE[_ZNK6dwarfs9metadata_INS_19debug_logger_policyEE4dumpERSoiRKNS_15filesystem_infoERKSt8functionIFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjEE]+0x4b8): more undefined references to `fmt::v8::vformat[abi:cxx11](fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/dwarfsbench.dir/build.make:118: dwarfsbench] Error 1
make[1]: *** [CMakeFiles/Makefile2:599: CMakeFiles/dwarfsbench.dir/all] Error 2
/usr/bin/ld: folly/folly/experimental/exception_tracer/libfolly_exception_tracer.a(ExceptionStackTraceLib.cpp.o)(.debug_info+0x38): R_AARCH64_ABS64 used with TLS symbol _ZN12_GLOBAL__N_17invalidE
/usr/bin/ld: folly/folly/experimental/exception_tracer/libfolly_exception_tracer.a(ExceptionStackTraceLib.cpp.o)(.debug_info+0x5a): R_AARCH64_ABS64 used with TLS symbol _ZN12_GLOBAL__N_118uncaughtExceptionsE
/usr/bin/ld: folly/folly/experimental/exception_tracer/libfolly_exception_tracer.a(ExceptionStackTraceLib.cpp.o)(.debug_info+0x74): R_AARCH64_ABS64 used with TLS symbol _ZN12_GLOBAL__N_116caughtExceptionsE
/usr/bin/ld: folly/libfolly.a(CacheLocality.cpp.o)(.debug_info+0x13c2b): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly18SequentialThreadId3getEvE5local
/usr/bin/ld: folly/libfolly.a(AsyncStack.cpp.o)(.debug_info+0x64): R_AARCH64_ABS64 used with TLS symbol _ZN5folly12_GLOBAL__N_127currentThreadAsyncStackRootE
/usr/bin/ld: folly/folly/experimental/exception_tracer/libfolly_exception_tracer.a(ExceptionTracerLib.cpp.o)(.debug_info+0x132bf): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly15SharedMutexImplILb0EvSt6atomicNS_24SharedMutexPolicyDefaultEE26tls_lastDeferredReaderSlotEvE2tl
/usr/bin/ld: folly/folly/experimental/exception_tracer/libfolly_exception_tracer.a(ExceptionTracerLib.cpp.o)(.debug_info+0x1355d): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly15SharedMutexImplILb0EvSt6atomicNS_24SharedMutexPolicyDefaultEE21tls_lastTokenlessSlotEvE2tl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/mkdwarfs.dir/build.make:118: mkdwarfs] Error 1
make[1]: *** [CMakeFiles/Makefile2:564: CMakeFiles/mkdwarfs.dir/all] Error 2
/usr/bin/ld: folly/libfolly.a(SharedMutex.cpp.o)(.debug_info+0x6105): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly15SharedMutexImplILb1EvSt6atomicNS_24SharedMutexPolicyDefaultEE21tls_lastTokenlessSlotEvE2tl
/usr/bin/ld: folly/libfolly.a(SharedMutex.cpp.o)(.debug_info+0x613c): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly15SharedMutexImplILb1EvSt6atomicNS_24SharedMutexPolicyDefaultEE26tls_lastDeferredReaderSlotEvE2tl
/usr/bin/ld: folly/libfolly.a(SharedMutex.cpp.o)(.debug_info+0x61a3): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly15SharedMutexImplILb0EvSt6atomicNS_24SharedMutexPolicyDefaultEE21tls_lastTokenlessSlotEvE2tl
/usr/bin/ld: folly/libfolly.a(SharedMutex.cpp.o)(.debug_info+0x61da): R_AARCH64_ABS64 used with TLS symbol _ZZN5folly15SharedMutexImplILb0EvSt6atomicNS_24SharedMutexPolicyDefaultEE26tls_lastDeferredReaderSlotEvE2tl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/dwarfs_compat_test.dir/build.make:121: dwarfs_compat_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:528: CMakeFiles/dwarfs_compat_test.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by bdnbje** [comment]
building with gcc 8.3.0 throws these errors:
https://pastebin.com/CVkJAjQ1

**Comment by mhx** [comment]
Can you provide some more context?

The project builds/links/tests fine for me on `Linux archpi 5.11.4-1-ARCH #1 SMP Sun Mar 7 23:46:10 UTC 2021 aarch64 GNU/Linux`.

**Comment by bdnbje** [comment]
I built it today with kernel 'Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux' and it seemingly worked.
