### ISSUE TITLE
Unmounting the filesystem via fusermount sometimes does not terminate a dwarfs process

### ISSUE THREAD

**Issue by Phantop** [mhx/dwarfs#71]
This is an issue I just noticed is happening while using the `wip` branch with my [appdwarf](https://github.com/Phantop/appdwarf/blob/main/appdwarf) script. I can only get this to occur with the script, albeit consistently, but attempting to run the exact same commands manually does not reproduce this issue, which makes it all the more confusing.

Essentially, `dwarfs` runs correctly and mounts the image as expected, the image is unmounted as normal and I can verify that the mountpoint is gone, yet the `dwarfs` process continues to run. The file can be found [here](https://files.catbox.moe/e07je3.sh) (you must rename it to simply `pypy`), and is simply a `dwarfs` image with a header to mount, run, and unmount. Modifying the script to have the dwarfs process run in foreground but backgrounding it using an `&` appears to fix this issue, however it requires adding a delay using `sleep` which is undesirable.

As a side note, is there a way to get the PID of a dwarfs process? I would use "$!" but that doesn't appear to work with how dwarfs handles processes. Also, does dwarfs have a quiet mode of any sort? I've been redirecting stderr but if there's a built in quiet option that would be preferable.

**Comment by Phantop** [comment]
Some additional testing seems to indicate `-o tidy_strategy` being the culprit. I admit, that testing outside of the script, I have not been using the option, but using it is does reproduce it. The issue does not occur when `dwarfs` is run in the foreground.

**Comment by mhx** [comment]
> As a side note, is there a way to get the PID of a dwarfs process?

There actually is! Try:

    getfattr -n user.dwarfs.driver.pid /path/to/mountpoint

> Some additional testing seems to indicate `-o tidy_strategy` being the culprit.

Very well spotted!

It's actually a bug that's bitten me before. The problem is that the tidying thread doesn't survive the fork into the background process when *not* running in the foreground. This should be easy to fix, I'll post here once it's done.

**Comment by mhx** [comment]
Can you please check if the commit I just pushed to `wip` fixes the issue for you?

**Comment by Phantop** [comment]
Yes that fixes the issue. Thanks!
