### ISSUE TITLE
new compression algo

### ISSUE THREAD

**Issue by bdnbje** [mhx/dwarfs#76]
this project could see some improvement in the compression ratio by using this [brotli](https://github.com/google/brotli).. It aims to be better than lzma or very close to it with zstd speeds.

**Comment by bdnbje** [comment]
Some tests i did: 
5570220	/home/chiro/lol2.tar
1513188	/home/chiro/lol.brotli
1599272	/home/chiro/lol.zstd
Decompression:
time zstd --long=28 --test ~/lol.zstd
real	0m6.682s
user 0m6.391s
sys	0m0.276s
time ~/brotli/out/brotli --test ~/lol.brotli
real	0m18.717s
user 0m18.197s
sys	0m0.452s

**Comment by mhx** [comment]
Thanks for the tests. I've also been running a few small tests last night using blocks extracted from a DwarFS image. This gives an exact estimate of how well a compression algorithm would perform in the context of DwarFS. The results were mixed purely from a compression ratio perspective. `brotli` compression was indeed better than `zstd`, in one case even *very slightly* better than `lzma`. However, compression was *significantly* slower.

What definitely interesting for the DwarFS use case is that `brotli` decompression uses a lot fewer resources (it's about 3x faster than `lzma`, but about 2x slower than `zstd`).

So I agree, it's definitely worth being added.

**Comment by mhx** [comment]
For reference:
```
6.4G    blocks
423M    brotli  (-Z --large_window=26)
415M    lzma    (-9)
467M    zstd    (--ultra -22 --long)

zstd:
real    0m0.686s
user    0m6.665s
sys     0m3.602s

brotli:
real    0m1.366s
user    0m13.457s
sys     0m6.897s

lzma:
real    0m3.570s
user    0m43.533s
sys     0m2.158s
```

**Comment by mhx** [comment]
Please check out the v0.7.0-RC1 release candidate: https://github.com/mhx/dwarfs/releases/tag/v0.7.0-RC1

**Comment by bdnbje** [comment]
brotli works insanely well with dwarfs. It even beats out lzma with extreme settings on my data set of a bunch of roms.
'''[chiro@archlinux build]$ wc -c snes*
1442125138 snes.chdbr (brotli 9 window size 26)
1444930775 snes.chdlz(lzma 9 extreme)
1508683062 snes.chdz(zstd level22)'''

extract times:
'''[chiro@archlinux build]$ time ./dwarfsextract -i snes.chdbr -o lol -n 16

real	1m17.250s
user	0m22.700s
sys	0m4.812s
[chiro@archlinux build]$ time ./dwarfsextract -i snes.chdbr -o lol -n 16

real	1m3.321s
user	0m21.146s
sys	0m4.746s
[chiro@archlinux build]$ time ./dwarfsextract -i snes.chdz -o lol -n 16

real	1m1.389s
user	0m8.113s
sys	0m3.158s'''

**Comment by brunoais** [comment]
It appears like zstd is best for testing and brotli is best for production version. AWESOME!

**Comment by mhx** [comment]
Cool, I'm closing this then!
