### ISSUE TITLE
Feature request: dwarfsextract for windows

### ISSUE THREAD

**Issue by sgmihai** [mhx/dwarfs#85]
I think it would be nice if .dwarfs images could be used on windows as well, as I don't know the odds of an archiver like 7zip adding support for this.
I tried to compile it with mingw, and I got:
dwarfsextract.cpp:26:10: fatal error: sys/statvfs.h: No such file or directory
I read that this is a unix header file, so it can't be used to compile for windows.

I'd like to know how hard would it be to port the code for dwarfextract to work on windows.

**Comment by mhx** [comment]
It should be fairly easy to drop the dependency on `sys/statvfs.h`. Currently this is only used to determine how many bytes to queue at most when extracting. It should be fairly easy to find a reasonable default in case `statvfs()` is unavailable.

**Comment by sgmihai** [comment]
That is good to hear. If you have time for a quick patch, I'd be glad to test it.

**Comment by mhx** [comment]
Will do, I'll let you know.

**Comment by mhx** [comment]
@sgmihai, you can check out the commit above and see if that gets you any further.

**Comment by mibmo** [comment]
Heyo. Sorry to bother, but I've been struggling with this for weeks now; how are you actually compiling it for windows, @sgmihai? Tried installing mingw and tons of dependencies but I'm just unable to get it to work, constantly getting compilations errors. I think I'm just encountering stupid simple issues that stem from not having developed on Windows in a decade. Would you mind letting me know how you got as far as you did? (or maybe just providing some resource? I'm really grasping at straws here! :) Nonetheless any help is greatly appreciated)

**Comment by sgmihai** [comment]
@mibmo I think it was just x86_64-w64-mingw32-g++ dwarfsextract.cpp that I tried.
dwarfsextract is the only tool you need to extract on windows. The other parts of dwarfs were not of interest to me, and things like mounting cannot work, as there is no FUSE on windows.
I must have hit another compile roadblock after @mhx submitted that fix and gave up on it. Sorry for not reporting further. Welcome to try and report results so we can reopen this issue, as it is not fixed ?

**Comment by mibmo** [comment]
@sgmihai no worries! Thanks for getting back nonetheless! :)

I'll see if I can get it to compile again. The parts I'm still iffy about are what dependencies to have installed and how to even set up a toolchain on windows, but I'm sure there's at least an online guide for the latter. I'll report back when I get to it :)

**Comment by mhx** [comment]
> @mhx: do you reckon it'd be possible to integrate dwarfs into a separate file manager solution, or would it perhaps become hell to keep up with the changes to the format? Curious as to what you have to say! If the dwarfs format is fairly stable, then that would definitely be something I'd like to look into :) 

This seems like a somewhat orthogonal problem (relative to Windows compilation) to me. Ultimately, except for the FUSE driver, it should be possible to port all the code to Windows. Also, it should be possible to integrate the code into a file manager (but that wouldn't have to be limited to Windows). Under the hood, most of dwarfs is designed as a library, e.g. [`filesystem_v2`](https://github.com/mhx/dwarfs/blob/main/include/dwarfs/filesystem_v2.h) is the class that's being used to access data in a DwarFS image.

That being said, certain areas of the codebase are quite Linux-specific. I think I've tried to wrap them in a lot of places so they can be swapped out of other platform-specific implementations (e.g. [`mmif`](https://github.com/mhx/dwarfs/blob/main/include/dwarfs/mmif.h)/[`mmap`](https://github.com/mhx/dwarfs/blob/main/include/dwarfs/mmap.h)). There are quite likely areas where I've forgotten to do this, though.

Regarding the format, I'd think it's relatively stable. I do anticipate a few changes in the future, but nothing that I would expect to be a compatibility nightmare. But hey, you never know for sure. :) One thing to note about the format, however, is that while there's both [a high level overview](https://github.com/mhx/dwarfs/blob/main/doc/dwarfs-format.md) as well as [a formal definition](https://github.com/mhx/dwarfs/blob/main/thrift/metadata.thrift), these don't fully define the format on a bit level. The most complex part of the format is the metadata, which is defined in [Thrift](https://github.com/facebook/fbthrift/) and serialized using the [Frozen](https://github.com/facebook/fbthrift/blob/main/thrift/lib/cpp2/frozen/Frozen.h#L56-L84) library. Trying not to use Thrift/Frozen would likely be a major headache.

**Comment by nieyuanhong** [comment]
Windows also has FUSE, maybe https://github.com/winfsp/winfsp can help us.

**Comment by Efreak** [comment]
I'd be interested in something like this for Windows/WinFsp, assuming it has decent read speed. I have a large number of older games (c&c games name a big option of this) with add many as 15 copies each for mods (ra2 and tibed each have over a dozen), and currently I'm just using hard links to keep the directory size manageable. Pretty sure the total size is somewhere in the 100-200gb range, but size on disk is around 15gb. I would be far happier if I could get this small enough to keep on one of my flash drives, and just use a union filesystem to deal with writes and occasional config changes. 

Now that I've seen this, I'm wondering how well the windows version of rclone works with union filesystems.

**Comment by CheerfulPianissimo** [comment]
It would also be pretty useful if a dwarfsextract.exe binary is included in future [releases](https://github.com/mhx/dwarfs/releases/) . As of now, dwarfs as a archival format is of limited use for non-technical Windows users because of the lack of an easily accessible extractor. Even for technical users it is something of a pain to extract dwarfs archives on windows without resorting to WSL or virtual machines. Having a binary build for it should improve accessibility of the format as an archival/distribution solution outside linux/macos.

**Comment by sgmihai** [comment]
Great news ! A lot better than nothing. Please find a way to make those binaries available soon.

**Comment by mhx** [comment]
Please give this a try. I've done a bit of testing with these binaries, but I've got only a few weeks of Windows experience.

[dwarfs-0.7.0-win-prerelease1-Windows.zip](https://github.com/mhx/dwarfs/files/11905597/dwarfs-0.7.0-win-prerelease1-Windows.zip)

I've updated the [README](https://github.com/mhx/dwarfs/tree/mhx/windows-build#windows-support) to include some information on the Windows version. The code is currently on the [windows-build](https://github.com/mhx/dwarfs/tree/mhx/windows-build) branch.

Keep in mind that in order to use the DwarFS FUSE driver, [WinFsp](https://github.com/winfsp/winfsp) must be installed and its DLL must be discoverable by `dwarfs.exe` (e.g. you could just copy the DLL to the same directory).

All other tools should hopefully work pretty much the same as their Linux counterparts.

**Comment by mhx** [comment]
> I'd be interested in something like this for Windows/WinFsp, assuming it has decent read speed. [...]

@Efreak, I've [opened a discussion](https://github.com/orgs/winfsp/discussions/514) over at WinFsp regarding performance. Right now, the WinFsp/FUSE version's speed is neither great nor terrible, but definitely slower than the Linux FUSE version.

I'd appreciate if you could give the prerelease binaries a try!

**Comment by mhx** [comment]
> @mhx: do you reckon it'd be possible to integrate dwarfs into a separate file manager solution, or would it perhaps become hell to keep up with the changes to the format?

@mibmo, with the WinFsp/FUSE driver, DwarFS images can be mounted either as a directory or as a separate drive, so no need for a separate file manager solution. :)

**Comment by mibmo** [comment]
@mhx thank you so much for you work! This was already incredible but this is just an amazing cherry on top. :)

**Comment by mhx** [comment]
> @mhx thank you so much for you work! This was already incredible but this is just an amazing cherry on top. :)

@mibmo Did you get a chance to play with the Windows binaries? I'd really like to know if there are any issues. :)

**Comment by mhx** [comment]
I've put up a release candidate that includes Windows binaries. I'll close this for now.
