### ISSUE TITLE
Option to unmount by force

### ISSUE THREAD

**Issue by miocrime** [mhx/dwarfs#88]
Hello, so I am using your tool in a project of mine. But I have a little problem that could be fixed on the side of dwarfs.

Say that you use dwarfs for running games or programs while being compressed, but then want it to unmount automatically with your bash script with which you ran it. (I do) The program may in some cases leave zombie processes or take very long to close, probably more likely on windows programs through wine.

In this case, a trap command that runs the unmounting of the dwarfs mounted directory after the bash script ran the program will fail because the device is busy. I tried ways to kill all processes before the unmounting happens but it doesn't work well and I think it can be done better.

So, what if dwarfs has a flag option for unmounting that kills all processes which depend on the device before it attempts to unmount. I hope this makes sense and thank you!

CORRECTION: Forgot that dwarfs is not used for unmounting, but fuse with fusermount -u. But still maybe can be handled by dwarfs.

**Comment by Phantop** [comment]
Hey, so I do something very similar with my [appdwarf](https://github.com/Phantop/appdwarf) project. I've had generally decent luck just doing `fusermount -uz`, which does lazy unmounting (filesystem is immediately no longer exposed, dwarfs closes when no more files are being accessed).

**Comment by miocrime** [comment]
Turns out I can use fuser -k and it works perfectly.

The issue can be closed, or perhaps not if the dev wants to implement it into dwarfs.

**Comment by miocrime** [comment]
No longer need it on dwarfs side
