### ISSUE TITLE
Symbol Lookup Error

### ISSUE THREAD

**Issue by Abhinav1217** [mhx/dwarfs#89]
I downloaded the release and moved the files appropriately. When I ran it, I ran into some .so not found issues that I resolved using symlinks. But now I am looking at a Symbol lookup error and I have no Idea what it is.

```
abhinav@abhinav-sol ~ $ dwarfs
dwarfs: symbol lookup error: dwarfs: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciilMNS_10LogMessageEFvvE
```
Can someone shed some light on how to fix this?

When I was moving man files, I ran into some prompt that moving man1,man5 wants to change folder permission. I said no to that, it moved the files but didn't change the permission on the folder. Does that caused this issue? It is only man pages right?

Distro Information:

Solus OS 64bit (Gnome edition) Updated.
```
abhinav@abhinav-sol ~ $ gnome-shell --version
GNOME Shell 42.0

abhinav@abhinav-sol ~ $ uname -a
Linux abhinav-sol 5.15.43-215.current #1 SMP PREEMPT Sun May 29 09:34:51 UTC 2022 x86_64 GNU/Linux
```

**Comment by mhx** [comment]
Hi @Abhinav1217, thanks for the report!

This is *really* strange. If you downloaded a dwarfs release from the release page, the binaries should *not* require *any* `.so` files. Also, there shouldn't be *any* symbol lookup errors.

To elaborate: the binaries contained in the release tarball are statically linked, i.e. they come bundled with _almost_ everything they need in order to work on pretty much any Linux distribution. It's _almost_ because the FUSE drivers (`dwarfs`, `dwarfs2`) require the FUSE userspace tools & kernel drivers to be present on the system.

So you shouldn't really have to symlink shared libraries in order to get the binaries to work.

That being said, I'm completely unfamiliar with Solus OS and my attempts to get it to run on VirtualBox have so far been unsuccessful (whenever I'm about to do anything meaningful, I get an "oh no, something something, you have to log out" message).

Could you do me a favour and please *undo all symlinks* you've made, confirm which dwarfs release you've downloaded, and show me the output of running `mkdwarfs` and `dwarfs` with their full path (you can run them directly from the extracted tarball), i.e.:

```
$ wget -q https://github.com/mhx/dwarfs/releases/download/v0.6.1/dwarfs-0.6.1-Linux.tar.bz2
$ tar xf dwarfs-0.6.1-Linux.tar.bz2 
$ ./dwarfs-0.6.1-Linux/bin/mkdwarfs 
mkdwarfs (v0.6.1)

Command line options:
  -i [ --input ] arg                    path to root directory or source 
                                        filesystem
[...]
$ ./dwarfs-0.6.1-Linux/sbin/dwarfs  
dwarfs (v0.6.1, fuse version 35)

usage: ./dwarfs-0.6.1-Linux/sbin/dwarfs image mountpoint [options]

DWARFS options:
    -o cachesize=SIZE      set size of block cache (512M)
[...]
```

FWIW, I've just tried this on a *really* old Debian Wheezy live image and it worked just fine.

**Comment by Phantop** [comment]
Also jumping in that I am a Solus user and have used the releases with no issue. Odd they're looking up symbols... the latest ones should be statically linked.

If you want to have a working dynamic build I made a package.yml [here](https://github.com/Phantop/solus-stuff/blob/main/dwarfs/package.yml).

**Comment by mhx** [comment]
Thanks @Phantop, definitely helpful to know that this is not a general issue on this distro.

**Comment by Abhinav1217** [comment]
@mhx 
> he binaries should not require any .so files. Also, there shouldn't be any symbol lookup errors.

It asked for libglog.so.1, I ran `fd libglog /` and found a libglog.so.0 which I symlinked to libglog.so.1 . That is the only change I made to run it 

Here are the steps I did @Phantop can you have a look at it, maybe I did some steps wrong.

1. Downloaded latest linux tar.gz and extracted it in a temp folder. 
2. l Moved everything from  temp/bin to /usr/bin
3. Moved everything from temp/sbin to /usr/sbin
4. Moved everything from temp/share/man/* to /usr/share/man/ 
5. When I was moving the man files, I was prompted that moving this folder would change the permission, do I want to change it, I said no, and it moved without changing permission.
6. symlinked libglog.so.1 to libglog.so.0 to fix the issue of missing library.


@Phantop : How do I use your package.yml? I have built eopkg packages using pspec.xml but that command is not working for package.yml. There is no readme on your solus-stuff repo.

**Comment by mhx** [comment]
@Abhinav1217, none of the moving around is relevant.

Can you please run the series of commands from my initial reply and paste the output here?

**Comment by Abhinav1217** [comment]
Well this is awkwardly confusing... 😕
 
```
abhinav@abhinav-sol ~/Application/Source/temp $ wget -q https://github.com/mhx/dwarfs/releases/download/v0.6.1/dwarfs-0.6.1-Linux.tar.bz2
abhinav@abhinav-sol ~/Application/Source/temp $ ls
dwarfs-0.6.1-Linux.tar.bz2
abhinav@abhinav-sol ~/Application/Source/temp $ tar xf dwarfs-0.6.1-Linux.tar.bz2
abhinav@abhinav-sol ~/Application/Source/temp $ ./dwarfs-0.6.1-Linux/bin/mkdwarfs
mkdwarfs (v0.6.1)

Command line options:
  -i [ --input ] arg                    path to root directory or source
                                        filesystem
  -o [ --output ] arg                   filesystem output name
.....
.....

abhinav@abhinav-sol ~/Application/Source/temp $ ./dwarfs-0.6.1-Linux/sbin/dwarfs
dwarfs (v0.6.1, fuse version 35)

usage: ./dwarfs-0.6.1-Linux/sbin/dwarfs image mountpoint [options]

DWARFS options:
    -o cachesize=SIZE      set size of block cache (512M)

.....
.....
```

But the one I copied yesterday in my system path shows the error
```
abhinav@abhinav-sol ~/Application/Source/temp $ dwarfs
dwarfs: symbol lookup error: dwarfs: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciilMNS_10LogMessageEFvvE
abhinav@abhinav-sol ~/Application/Source/temp $ mkdwarfs
mkdwarfs: symbol lookup error: mkdwarfs: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciilMNS_10LogMessageEFvvE
```

**Comment by Phantop** [comment]
> How do I use your package.yml? I have built eopkg packages using pspec.xml but that command is not working for package.yml. There is no readme on your solus-stuff repo.

I am... unfamiliar with building packages from a pspec file alone? My understanding of the Solus packaging system is you build from a package.yml and a pspec is part of the result.

You just need to clone the repo recursively and follow the guide [here](https://getsol.us/articles/packaging/building-a-package/en/).
