### ISSUE TITLE
FUSE daemon `-o cachesize` issue

### ISSUE THREAD

**Issue by cipriancraciun** [mhx/dwarfs#9]
So I've created quite a largish image, of about 800 MiB, which uncompressed had around 2.5 GiB.

I've tried starting `dwarfs` with `-o cachesize=128m`, ran a `find /tmp/dwarfs -type f -exec md5sum {} +` and after it was done the FUSE daemon process still retains ~800 MiB to ~1 GiB of RAM.  (This is not the virtual memory, but instead the `RES` column of `htop` which reports the actual memory committed.  When `dwarfs` starts it reports ~ 150 MiB.)

Now given that there are no more any open files, and the fact that I've already passed through all the files, there shouldn't be any uncompressed blocks (thus uncompression state) lingering around.

Even using an uncompressed image (i.e. `-l 0`) of ~400 MiB uncompressed size, results in ~400 MiB RAM usage.

**Comment by mhx** [comment]
This sounds like basically all of the compressed file system has been paged into process memory as you've ensured that all blocks were eventually accessed. So I'd expect the RSS reported to be around (filesystemsize + cachesize), which I think is pretty much what you're seeing. The memory will be paged out again if it's required elsewhere. The only thing that you *can choose* to lock into memory (via `-o mlock`) is the metadata block, but the actual data blocks will never be locked. The `-o cachesize` only affects the number of *uncompressed* blocks kept in memory.

If you run another process that's using up large amounts of memory (something like `perl -e'@a=(1)x100000000'`), you'll likely find that RSS of the `dwarfs` process drops back to around what you specified for `-o cachesize`.

**Comment by cipriancraciun** [comment]
Granted you might be right.  Next time that I try DwarFS, I'll issue a `sysctl -q vm.drop_caches=3` which if I'm not mistaken should drop the kernel file-system caches.

----

(In what follows I refer to the `dwarfs` image as just `image`, and to the uncompressed files exposed through the mount point as `files`.)

However, on the same topic, wouldn't it be useful to have the following complementary options:
* whether to let the kernel cache the files (not the image), like all normal file-systems do;  (I think this is the default;)
* whether `dwarfs` daemon accesses the image without using the kernel cache (either via `O_DIRECT` or by using `madvise` with `MADV_DONTNEED` in case of `mmap` access after a block was used);

At the moment I think that both the files and the image are eventually cached by the kernel, thus increasing the memory pressure of the system.

However by using the two proposed options, one could fine tune the CPU / memory usage to fit one's particular use-case:
* disable the kernel cache for the files, but enable the kernel cache for the image, one trades CPU for and saves some memory;  (useful for example when the application reading the files already has its own caches;)
* (my proposed default) enable the kernel cache for files, but disable the kernel cache for the image, one saves on memory for the image but trades some CPU (less than in the previous case); (I think this would be the closest thing to how a normal file-system works, only actual files are cached, but not the block device data;)
* disable the kernel cache for both files and image, one would heavily trade CPU for minimal memory usage;  (this would be useful for example when one needs only a single pass of the stored files;)
* (the current default?) enable the kernel cache for both files and image, one would trade memory for minimal CPU usage;

**Comment by mhx** [comment]
I definitely like the idea!

I've been playing around a bit with `O_DIRECT` and `madvise()`, but I can't get [my test code](https://gist.github.com/mhx/7867a62e99d7113dfc1ed116799da84d) to actually free up RSS after scanning the whole mapping. If you have an idea what's going on, please let me know :)

**Comment by cipriancraciun** [comment]
> I've been playing around a bit with O_DIRECT and madvise(), but I can't get my test code to actually free up RSS after scanning the whole mapping. If you have an idea what's going on, please let me know :)

My assumption (the manual doesn't state anything about this) is that you should call `madvise` with `MADV_DONTNEED` after each read to tell the kernel that you don't need the memory you've just read.

BTW, there is also `posix_fadvise` that has support for `POSIX_FADV_DONTNEED` in case you don't want to use `O_DIRECT`.  However like in the case of `madvise` I think you should call `posix_fadvise` after each complete read.

**Comment by mhx** [comment]
I did try calling it before and after the reads, using both the `posix_` and regular versions, with and without `O_DIRECT`. Doesn't seem to affect RSS at all, which is contrary to what the manual says (RSS should drop immediately even if the kernel is allowed to delay the actual freeing).

Don't ask me what I did differently last night, but I just re-tried with the same code, and it worked. Nothing a good night's sleep can't fix, apparently...

**Comment by cipriancraciun** [comment]
So after a bit of experimenting, even if using `-o cachesize=256m` and after reading the entire file-system (in walk order) and after issuing `sysctl vm.drop_caches=3` the memory usage of `dwarfs` FUSE driver is still too high than expected:

The following is the important section from `/proc/$PID/status`:
~~~~
VmPeak: 17186068 kB
VmSize: 14350252 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:  12058004 kB
VmRSS:  12028616 kB
RssAnon:         2315696 kB
RssFile:         9712920 kB
RssShmem:              0 kB
VmData:  3320500 kB
VmStk:       132 kB
VmExe:      3948 kB
VmLib:         4 kB
VmPTE:     24600 kB
VmSwap:        0 kB
~~~~

The important figure here is `RssAnon` which according to the manual: `Size of resident anonymous memory.`, which I'm assuming is actually the memory backing `malloc` (or similar).

Although the documentation states it's "innacurate", my guess that the accuracy is at least 90%.  However if you would like I can also attach the contents of `smaps`.  Bellow is the contents of `/proc/$PID/smaps_rollup`, which does indicate the same thing.
~~~~
00400000-7ffed3c67000 ---p 00000000 00:00 0                              [rollup]
Rss:            12049800 kB
Pss:            12049796 kB
Pss_Anon:        2315988 kB
Pss_File:        9733808 kB
Pss_Shmem:             0 kB
Shared_Clean:          4 kB
Shared_Dirty:          0 kB
Private_Clean:   9733808 kB
Private_Dirty:   2315988 kB
Referenced:     12049800 kB
Anonymous:       2315988 kB
LazyFree:              0 kB
AnonHugePages:   1746944 kB
ShmemPmdMapped:        0 kB
Shared_Hugetlb:        0 kB
Private_Hugetlb:       0 kB
Swap:                  0 kB
SwapPss:               0 kB
Locked:                0 kB
~~~~

----

Perhaps it would be a good idea to just drop internal compression states (and other caches) if not used for a particular amount of time (configurable).

**Comment by mhx** [comment]
I think what we're seeing is mostly allocator behaviour:

    $ ./dwarfs perl-install.dwarfs mnt -f -o cachesize=64m
    $ ls mnt/*/*/bin/perl5* | sed -e's/^/if=/' | xargs -d $'\n' -P20 -n1 dd status=none of=/dev/null
    $ cat /proc/$(pgrep dwarfs)/status | grep ^Rss
    RssAnon:          761320 kB
    RssFile:           25920 kB
    RssShmem:              0 kB

    $ LD_PRELOAD="/usr/lib64/libtcmalloc.so" ./dwarfs perl-install.dwarfs mnt -f -o cachesize=64m
    $ ls mnt/*/*/bin/perl5* | sed -e's/^/if=/' | xargs -d $'\n' -P20 -n1 dd status=none of=/dev/null
    $ cat /proc/$(pgrep dwarfs)/status | grep ^Rss
    RssAnon:          292736 kB
    RssFile:           27020 kB
    RssShmem:              0 kB

    $ LD_PRELOAD="/usr/lib64/libjemalloc.so" ./dwarfs perl-install.dwarfs mnt -f -o cachesize=64m
    $ ls mnt/*/*/bin/perl5* | sed -e's/^/if=/' | xargs -d $'\n' -P20 -n1 dd status=none of=/dev/null
    $ cat /proc/$(pgrep dwarfs)/status | grep ^Rss
    RssAnon:           91316 kB
    RssFile:           27308 kB
    RssShmem:              0 kB

As you can see, there's almost an order of magnitude difference between jemalloc and the default glibc malloc. (Reminds me that it's probably a good idea to ship the statically linked binaries with jemalloc.)

I've actually captured heap profiles of the `dwarfs` process and can't see anything suspicious. Most of the memory is owned by blocks in the cache, some memory is in the fuse layer which is not under my control anyway. The remainder of the RSS is likely just sitting around unused in the allocator.

During active FUSE requests, a lot more blocks than configured by `-o cachesize` can be in flight, which I think is why glibc malloc memory goes through the roof, especially when multiple FUSE requests are made concurrently:

    $ ./dwarfs perl-install.dwarfs mnt -f -o cachesize=64m
    $ time ls mnt/*/*/bin/perl5* | sed -e's/^/if=/' | xargs -d $'\n' -P1 -n1 dd status=none of=/dev/null
    $ cat /proc/$(pgrep dwarfs)/status | grep ^Rss
    RssAnon:          251760 kB
    RssFile:           23924 kB
    RssShmem:              0 kB

That's with `-P1` instead of `-P20` above, and suddenly `RssAnon` drops by a factor of 3. For jemalloc, there's no difference.

It's definitely possible to put a limit on the number of blocks in flight at the cost of speed.

> Perhaps it would be a good idea to just drop internal compression states (and other caches) if not used for a particular amount of time (configurable).

There's only one cache: the one for decompressed blocks. The decompressor itself is deallocated as soon as the data has been fully decompressed. Evicting blocks from the cache after some time could certainly be done.

There's also `malloc_trim()`, but it does a pretty poor job and still leaves glibc malloc behind tcmalloc or jemalloc.

**Comment by cipriancraciun** [comment]
I understand your point from the previous analysis.  However on a laptop with 8 GiB RAM, having 2 GiB eaten by DwarFS is kind of a show-stopper...

It would be wonderful if we find a way to tell `malloc` to drop anonymous pages more quickly, or at least to drop holes in the memory pages.

If you make large allocation, you could perhaps use `madvise` and `MADV_DONTNEED`, whose manual states:
~~~~

              After a successful MADV_DONTNEED operation, the semantics of
              memory access in the specified region are changed: subsequent
              accesses of pages in the range will succeed, but will result
              in either repopulating the memory contents from the up-to-date
              contents of the underlying mapped file (for shared file
              mappings, shared anonymous mappings, and shmem-based
              techniques such as System V shared memory segments) or zero-
              fill-on-demand pages for anonymous private mappings.
~~~~

Or perhaps the Linux specific `MADV_REMOVE` or `MADV_FREE` (see [manual](https://www.man7.org/linux/man-pages/man2/madvise.2.html)).

**Comment by mhx** [comment]
I already pushed a commit earlier that switches all binaries to jemalloc.
