### ISSUE TITLE
mkdwarfs replaces existing image with empty one if ran in same dir and source dir does not exist

### ISSUE THREAD

**Issue by miocrime** [mhx/dwarfs#93]
I had lost some data due to this, it is user error but mkdwarfs should not just replace an existing image without asking, I believe...

**Comment by mhx** [comment]
I'm sorry to hear you lost data, but yes, this is how `mkdwarfs` currently behaves.

I'll change the default so `mkdwarfs` will refuse to run if the output file exists, and add a `--force` switch to override.
