### ISSUE TITLE
No self-kill when running out of ram with mkdwarfs

### ISSUE THREAD

**Issue by adminx01** [mhx/dwarfs#97]
Only happened twice to me so i'm not really sure about it.

**Comment by Phantop** [comment]
Do you mean that your system hangs due to lack of an OOM kill?

If so, this may be related to the age old issue of Linux not killing stuff fast enough and hanging for ages. `earlyoom` helps with that.

**Comment by mhx** [comment]
Mmmh, I'm not entirely sure if self-kill is really what you want. I think it'd be really frustrating if your system ran low on memory and an `mkdwarfs` process that has been running for half an hour killed itself just because Chrome was eating up all of the RAM.

> I think most other compression tools have ability to cancel themselves

Can you provide some pointers? I'm not actually aware of this.

**Comment by mhx** [comment]
> Well I think zpaq shows in terminal "killed" or something like that.

I'm reasonably certain that this message is from the shell, not from zpaq, informing you that the zpaq process has been killed, likely by the OOM killer.

Did it look anything like this?

```
% tail /dev/zero
zsh: killed     tail /dev/zero
```

If so, that's the OOM killer.

**Comment by mhx** [comment]
> Well I think zpaq shows in terminal "killed" or something like that.

I'm reasonably certain that this message is from the shell, not from zpaq, informing you that the zpaq process has been killed, likely by the OOM killer.

Did it look anything like this?

```
% tail /dev/zero
zsh: killed     tail /dev/zero
```

If so, that's the OOM killer.

**Comment by mhx** [comment]
I'll close this as I don't think self-kill is really what most people would expect.
